const WORD_POOLS = {
// Level 1: CET-4 四级词汇
  1: [
    {en:"abandon",cn:"放弃"},{en:"ability",cn:"能力"},{en:"able",cn:"能够的"},{en:"abnormal",cn:"异常的"},
    {en:"aboard",cn:"在船/车上"},{en:"abolish",cn:"废除"},{en:"about",cn:"关于"},{en:"above",cn:"在...上面"},
    {en:"abroad",cn:"在国外"},{en:"absence",cn:"缺席"},{en:"absent",cn:"缺席的"},{en:"absolute",cn:"绝对的"},
    {en:"absorb",cn:"吸收"},{en:"abstract",cn:"抽象的"},{en:"abundant",cn:"丰富的"},{en:"abuse",cn:"滥用"},
    {en:"academic",cn:"学术的"},{en:"academy",cn:"学院"},{en:"accelerate",cn:"加速"},{en:"accent",cn:"口音"},
    {en:"accept",cn:"接受"},{en:"acceptable",cn:"可接受的"},{en:"access",cn:"进入；访问"},{en:"accident",cn:"事故"},
    {en:"accommodate",cn:"容纳"},{en:"accompany",cn:"陪伴"},{en:"accomplish",cn:"完成"},{en:"account",cn:"账户"},
    {en:"accumulate",cn:"积累"},{en:"accurate",cn:"精确的"},{en:"accuse",cn:"指控"},{en:"accustom",cn:"使习惯"},
    {en:"achieve",cn:"实现"},{en:"achievement",cn:"成就"},{en:"acid",cn:"酸"},{en:"acknowledge",cn:"承认"},
    {en:"acquaintance",cn:"熟人"},{en:"acquire",cn:"获得"},{en:"across",cn:"穿过"},{en:"act",cn:"行动"},
    {en:"action",cn:"行动"},{en:"active",cn:"积极的"},{en:"activity",cn:"活动"},{en:"actor",cn:"演员"},
    {en:"actual",cn:"实际的"},{en:"adapt",cn:"适应"},{en:"add",cn:"增加"},{en:"addition",cn:"增加"},
    {en:"address",cn:"地址"},{en:"adequate",cn:"足够的"},{en:"adjust",cn:"调整"},{en:"administration",cn:"管理"},
    {en:"admire",cn:"钦佩"},{en:"admit",cn:"承认"},{en:"adopt",cn:"采用"},{en:"adult",cn:"成年人"},
    {en:"advance",cn:"前进"},{en:"advantage",cn:"优势"},{en:"adventure",cn:"冒险"},{en:"advertise",cn:"做广告"},
    {en:"advice",cn:"建议"},{en:"advise",cn:"建议"},{en:"advocate",cn:"提倡"},{en:"affair",cn:"事务"},
    {en:"affect",cn:"影响"},{en:"afford",cn:"负担得起"},{en:"afraid",cn:"害怕的"},{en:"after",cn:"在...之后"},
    {en:"afternoon",cn:"下午"},{en:"afterwards",cn:"后来"},{en:"again",cn:"再"},{en:"against",cn:"反对"},
    {en:"age",cn:"年龄"},{en:"agency",cn:"代理"},{en:"agent",cn:"代理人"},{en:"aggressive",cn:"侵略性的"},
    {en:"ago",cn:"以前"},{en:"agree",cn:"同意"},{en:"agreement",cn:"协议"},{en:"agriculture",cn:"农业"},
    {en:"ahead",cn:"在前面"},{en:"aid",cn:"援助"},{en:"aim",cn:"目标"},{en:"aircraft",cn:"飞机"},
    {en:"airline",cn:"航空公司"},{en:"airport",cn:"机场"},{en:"alarm",cn:"警报"},{en:"album",cn:"专辑"},
    {en:"alcohol",cn:"酒精"},{en:"alert",cn:"警觉的"},{en:"alien",cn:"外星人"},{en:"alike",cn:"相似的"},
    {en:"alive",cn:"活着的"},{en:"allow",cn:"允许"},{en:"allowance",cn:"津贴"},{en:"almost",cn:"几乎"},
    {en:"alone",cn:"单独的"},{en:"along",cn:"沿着"},{en:"alongside",cn:"在旁边"},{en:"alphabet",cn:"字母表"},
    {en:"already",cn:"已经"},{en:"alter",cn:"改变"},{en:"alternative",cn:"替代的"},{en:"although",cn:"虽然"},
    {en:"altogether",cn:"完全"},{en:"aluminum",cn:"铝"},{en:"always",cn:"总是"},{en:"amateur",cn:"业余的"},
    {en:"amaze",cn:"使惊奇"},{en:"ambition",cn:"野心"},{en:"ambulance",cn:"救护车"},{en:"among",cn:"在...之中"},
    {en:"amount",cn:"数量"},{en:"amuse",cn:"娱乐"},{en:"analyse",cn:"分析"},{en:"analysis",cn:"分析"},
    {en:"ancestor",cn:"祖先"},{en:"ancient",cn:"古代的"},{en:"anger",cn:"愤怒"},{en:"angle",cn:"角度"},
    {en:"angry",cn:"生气的"},{en:"animal",cn:"动物"},{en:"ankle",cn:"脚踝"},{en:"announce",cn:"宣布"},
    {en:"annoy",cn:"烦扰"},{en:"annual",cn:"年度的"},{en:"anonymous",cn:"匿名的"},{en:"another",cn:"另一个"},
    {en:"answer",cn:"回答"},{en:"anxiety",cn:"焦虑"},{en:"anxious",cn:"焦虑的"},{en:"anybody",cn:"任何人"},
    {en:"anyhow",cn:"无论如何"},{en:"anyone",cn:"任何人"},{en:"anything",cn:"任何事"},{en:"anyway",cn:"无论如何"},
    {en:"anywhere",cn:"任何地方"},{en:"apart",cn:"分开地"},{en:"apartment",cn:"公寓"},{en:"apologize",cn:"道歉"},
    {en:"apology",cn:"道歉"},{en:"apparent",cn:"明显的"},{en:"appeal",cn:"呼吁"},{en:"appear",cn:"出现"},
    {en:"appearance",cn:"外貌"},{en:"appetite",cn:"食欲"},{en:"apple",cn:"苹果"},{en:"application",cn:"申请"},
    {en:"apply",cn:"申请"},{en:"appoint",cn:"任命"},{en:"appointment",cn:"约会"},{en:"appreciate",cn:"感激"},
    {en:"approach",cn:"接近"},{en:"appropriate",cn:"适当的"},{en:"approve",cn:"批准"},{en:"approximate",cn:"大约的"},
    {en:"architect",cn:"建筑师"},{en:"area",cn:"区域"},{en:"argue",cn:"争论"},{en:"argument",cn:"争论"},
    {en:"arise",cn:"出现"},{en:"arithmetic",cn:"算术"},{en:"army",cn:"军队"},{en:"around",cn:"围绕"},
    {en:"arrange",cn:"安排"},{en:"arrest",cn:"逮捕"},{en:"arrival",cn:"到达"},{en:"arrive",cn:"到达"},
    {en:"arrow",cn:"箭"},{en:"art",cn:"艺术"},{en:"article",cn:"文章"},{en:"artificial",cn:"人工的"},
    {en:"artist",cn:"艺术家"},{en:"ashamed",cn:"羞愧的"},{en:"aside",cn:"在旁边"},{en:"aspect",cn:"方面"},
    {en:"assess",cn:"评估"},{en:"asset",cn:"资产"},{en:"assign",cn:"分配"},{en:"assist",cn:"协助"},
    {en:"associate",cn:"联系"},{en:"association",cn:"协会"},{en:"assume",cn:"假设"},{en:"assure",cn:"保证"},
    {en:"atmosphere",cn:"气氛"},{en:"attach",cn:"附上"},{en:"attack",cn:"攻击"},{en:"attain",cn:"达到"},
    {en:"attempt",cn:"尝试"},{en:"attend",cn:"参加"},{en:"attention",cn:"注意"},{en:"attitude",cn:"态度"},
    {en:"attorney",cn:"律师"},{en:"attract",cn:"吸引"},{en:"attraction",cn:"吸引力"},{en:"attractive",cn:"有吸引力的"},
    {en:"audience",cn:"观众"},{en:"authority",cn:"权威"},{en:"auto",cn:"汽车"},{en:"automatic",cn:"自动的"},
    {en:"automobile",cn:"汽车"},{en:"autumn",cn:"秋天"},{en:"available",cn:"可用的"},{en:"avenue",cn:"大道"},
    {en:"average",cn:"平均"},{en:"avoid",cn:"避免"},{en:"awake",cn:"醒着的"},{en:"award",cn:"奖"},
    {en:"aware",cn:"意识到的"},{en:"awful",cn:"糟糕的"},{en:"awkward",cn:"尴尬的"},{en:"bachelor",cn:"学士"},
    {en:"background",cn:"背景"},{en:"backward",cn:"向后的"},{en:"bacteria",cn:"细菌"},{en:"balance",cn:"平衡"},
    {en:"ball",cn:"球"},{en:"ban",cn:"禁止"},{en:"band",cn:"乐队"},{en:"bank",cn:"银行"},
    {en:"bar",cn:"酒吧"},{en:"bare",cn:"裸露的"},{en:"barely",cn:"几乎不"},{en:"bargain",cn:"便宜货"},
    {en:"barrier",cn:"障碍"},{en:"base",cn:"基础"},{en:"basic",cn:"基本的"},{en:"basin",cn:"盆"},
    {en:"basis",cn:"基础"},{en:"basket",cn:"篮子"},{en:"bat",cn:"蝙蝠"},{en:"bath",cn:"洗澡"},
    {en:"battery",cn:"电池"},{en:"battle",cn:"战斗"},{en:"bay",cn:"海湾"},{en:"beach",cn:"海滩"},
    {en:"bean",cn:"豆"},{en:"bear",cn:"承受"},{en:"beard",cn:"胡子"},{en:"beat",cn:"打败"},
    {en:"beautiful",cn:"美丽的"},{en:"beauty",cn:"美丽"},{en:"because",cn:"因为"},{en:"become",cn:"成为"},
    {en:"bedroom",cn:"卧室"},{en:"beef",cn:"牛肉"},{en:"beer",cn:"啤酒"},{en:"before",cn:"在...之前"},
    {en:"beg",cn:"乞求"},{en:"begin",cn:"开始"},{en:"behalf",cn:"代表"},{en:"behave",cn:"行为"},
    {en:"behavior",cn:"行为"},{en:"behind",cn:"在...后面"},{en:"belief",cn:"信念"},{en:"believe",cn:"相信"},
    {en:"bell",cn:"钟"},{en:"belong",cn:"属于"},{en:"beloved",cn:"心爱的"},{en:"below",cn:"在下面"},
    {en:"belt",cn:"带子"},{en:"bench",cn:"长椅"},{en:"bend",cn:"弯曲"},{en:"beneath",cn:"在下方"},
    {en:"benefit",cn:"利益"},{en:"beside",cn:"在旁边"},{en:"besides",cn:"此外"},{en:"best",cn:"最好的"},
    {en:"better",cn:"更好的"},{en:"between",cn:"在...之间"},{en:"beyond",cn:"超越"},{en:"bicycle",cn:"自行车"},
    {en:"bid",cn:"出价"},{en:"billion",cn:"十亿"},{en:"bind",cn:"绑"},{en:"biology",cn:"生物学"},
    {en:"bird",cn:"鸟"},{en:"birth",cn:"出生"},{en:"birthday",cn:"生日"},{en:"biscuit",cn:"饼干"},
    {en:"bitter",cn:"苦的"},{en:"blame",cn:"责备"},{en:"blank",cn:"空白的"},{en:"blanket",cn:"毯子"},
    {en:"bleed",cn:"流血"},{en:"blend",cn:"混合"},{en:"bless",cn:"祝福"},{en:"blind",cn:"盲的"},
    {en:"block",cn:"阻塞"},{en:"blood",cn:"血"},{en:"blow",cn:"吹"},{en:"blue",cn:"蓝色"},
    {en:"board",cn:"板"},{en:"boat",cn:"船"},{en:"body",cn:"身体"},{en:"boil",cn:"煮沸"},
    {en:"bold",cn:"大胆的"},{en:"bomb",cn:"炸弹"},{en:"bond",cn:"纽带"},{en:"bone",cn:"骨头"},
    {en:"book",cn:"书"},{en:"boom",cn:"繁荣"},{en:"boost",cn:"促进"},{en:"boot",cn:"靴子"},
    {en:"border",cn:"边界"},{en:"bore",cn:"使无聊"},{en:"born",cn:"出生的"},{en:"borrow",cn:"借"},
    {en:"boss",cn:"老板"},{en:"bother",cn:"打扰"},{en:"bottle",cn:"瓶子"},{en:"bottom",cn:"底部"},
    {en:"bounce",cn:"弹跳"},{en:"boundary",cn:"边界"},{en:"bow",cn:"鞠躬"},{en:"bowl",cn:"碗"},
    {en:"box",cn:"盒子"},{en:"brain",cn:"大脑"},{en:"branch",cn:"分支"},{en:"brand",cn:"品牌"},
    {en:"brave",cn:"勇敢的"},{en:"bread",cn:"面包"},{en:"break",cn:"打破"},{en:"breakfast",cn:"早餐"},
    {en:"breath",cn:"呼吸"},{en:"breathe",cn:"呼吸"},{en:"breed",cn:"品种"},{en:"brick",cn:"砖"},
    {en:"bridge",cn:"桥"},{en:"brief",cn:"简短的"},{en:"bright",cn:"明亮的"},{en:"brilliant",cn:"辉煌的"},
    {en:"bring",cn:"带来"},{en:"broad",cn:"宽的"},{en:"broadcast",cn:"广播"},{en:"brother",cn:"兄弟"},
    {en:"brush",cn:"刷子"},{en:"budget",cn:"预算"},{en:"build",cn:"建造"},{en:"building",cn:"建筑物"},
    {en:"bulk",cn:"大量"},{en:"bullet",cn:"子弹"},{en:"bunch",cn:"束"},{en:"burden",cn:"负担"},
    {en:"burn",cn:"燃烧"},{en:"burst",cn:"爆发"},{en:"bury",cn:"埋葬"},{en:"bus",cn:"公共汽车"},
    {en:"bush",cn:"灌木"},{en:"business",cn:"生意"},{en:"busy",cn:"忙碌的"},{en:"button",cn:"按钮"},
    {en:"calculate",cn:"计算"},{en:"calendar",cn:"日历"},{en:"call",cn:"叫"},{en:"calm",cn:"平静的"},
    {en:"camera",cn:"相机"},{en:"camp",cn:"营地"},{en:"campaign",cn:"运动"},{en:"campus",cn:"校园"},
    {en:"cancel",cn:"取消"},{en:"cancer",cn:"癌症"},{en:"candidate",cn:"候选人"},{en:"capable",cn:"有能力的"},
    {en:"capacity",cn:"容量"},{en:"capital",cn:"首都"},{en:"capture",cn:"捕获"},{en:"carbon",cn:"碳"},
    {en:"card",cn:"卡片"},{en:"care",cn:"关心"},{en:"career",cn:"职业"},{en:"careful",cn:"仔细的"},
    {en:"cargo",cn:"货物"},{en:"carry",cn:"携带"},{en:"case",cn:"案例"},{en:"cash",cn:"现金"},
    {en:"cast",cn:"投"},{en:"casual",cn:"随意的"},{en:"cat",cn:"猫"},{en:"catalog",cn:"目录"},
    {en:"catch",cn:"抓住"},{en:"category",cn:"类别"},{en:"cause",cn:"原因"},{en:"cease",cn:"停止"},
    {en:"celebrate",cn:"庆祝"},{en:"cell",cn:"细胞"},{en:"center",cn:"中心"},{en:"central",cn:"中心的"},
    {en:"century",cn:"世纪"},{en:"ceremony",cn:"仪式"},{en:"certain",cn:"确定的"},{en:"chain",cn:"链"},
    {en:"chair",cn:"椅子"},{en:"chairman",cn:"主席"},{en:"challenge",cn:"挑战"},{en:"champion",cn:"冠军"},
    {en:"chance",cn:"机会"},{en:"change",cn:"改变"},{en:"channel",cn:"频道"},{en:"chapter",cn:"章节"},
    {en:"character",cn:"角色"},{en:"charge",cn:"收费"},{en:"charity",cn:"慈善"},{en:"chart",cn:"图表"},
    {en:"chase",cn:"追逐"},{en:"cheap",cn:"便宜的"},{en:"cheat",cn:"作弊"},{en:"check",cn:"检查"},
    {en:"cheese",cn:"奶酪"},{en:"chemical",cn:"化学的"},{en:"chest",cn:"胸部"},{en:"chicken",cn:"鸡"},
    {en:"chief",cn:"主要的"},{en:"child",cn:"孩子"},{en:"childhood",cn:"童年"},{en:"chip",cn:"芯片"},
    {en:"chocolate",cn:"巧克力"},{en:"choice",cn:"选择"},{en:"choose",cn:"选择"},{en:"church",cn:"教堂"},
    {en:"cigarette",cn:"香烟"},{en:"cinema",cn:"电影院"},{en:"circle",cn:"圆"},{en:"circumstance",cn:"情况"},
    {en:"citizen",cn:"公民"},{en:"city",cn:"城市"},{en:"civil",cn:"民事的"},{en:"claim",cn:"声称"},
    {en:"clarify",cn:"澄清"},{en:"class",cn:"班级"},{en:"classic",cn:"经典的"},{en:"classroom",cn:"教室"},
    {en:"clean",cn:"干净的"},{en:"clear",cn:"清楚的"},{en:"clerk",cn:"职员"},{en:"clever",cn:"聪明的"},
    {en:"click",cn:"点击"},{en:"client",cn:"客户"},{en:"climate",cn:"气候"},{en:"climb",cn:"爬"},
    {en:"clock",cn:"钟"},{en:"close",cn:"关闭"},{en:"cloth",cn:"布"},{en:"clothes",cn:"衣服"},
    {en:"cloud",cn:"云"},{en:"club",cn:"俱乐部"},{en:"coach",cn:"教练"},{en:"coal",cn:"煤"},
    {en:"coast",cn:"海岸"},{en:"code",cn:"代码"},{en:"coffee",cn:"咖啡"},{en:"coin",cn:"硬币"},
    {en:"cold",cn:"冷的"},{en:"collapse",cn:"倒塌"},{en:"colleague",cn:"同事"},{en:"collect",cn:"收集"},
    {en:"college",cn:"大学"},{en:"colony",cn:"殖民地"},{en:"color",cn:"颜色"},{en:"column",cn:"栏"},
    {en:"combine",cn:"结合"},{en:"come",cn:"来"},{en:"comfort",cn:"舒适"},{en:"command",cn:"命令"},
    {en:"comment",cn:"评论"},{en:"commercial",cn:"商业的"},{en:"commission",cn:"委员会"},{en:"commit",cn:"犯；承诺"},
    {en:"committee",cn:"委员会"},{en:"common",cn:"共同的"},{en:"communicate",cn:"沟通"},{en:"community",cn:"社区"},
    {en:"companion",cn:"同伴"},{en:"company",cn:"公司"},{en:"compare",cn:"比较"},{en:"compete",cn:"竞争"},
    {en:"competition",cn:"竞争"},{en:"complain",cn:"抱怨"},{en:"complete",cn:"完成"},{en:"complex",cn:"复杂的"},
    {en:"component",cn:"组件"},{en:"compose",cn:"组成"},{en:"composition",cn:"作文"},{en:"comprehend",cn:"理解"},
    {en:"computer",cn:"电脑"},{en:"concentrate",cn:"集中"},{en:"concept",cn:"概念"},{en:"concern",cn:"关心"},
    {en:"conclude",cn:"总结"},{en:"conclusion",cn:"结论"},{en:"concrete",cn:"具体的"},{en:"condition",cn:"条件"},
    {en:"conduct",cn:"进行"},{en:"conference",cn:"会议"},{en:"confess",cn:"承认"},{en:"confidence",cn:"信心"},
    {en:"confident",cn:"自信的"},{en:"confirm",cn:"确认"},{en:"conflict",cn:"冲突"},{en:"confuse",cn:"困惑"},
{en:"congress",cn:"国会"},{en:"connect",cn:"连接"},{en:"conscious",cn:"有意识的"},{en:"consensus",cn:"共识"},
    {en:"consequence",cn:"后果"},{en:"conservative",cn:"保守的"},{en:"consider",cn:"考虑"},{en:"consist",cn:"由...组成"},
    {en:"constant",cn:"恒定的"},{en:"construct",cn:"建造"},{en:"construction",cn:"建设"},{en:"consult",cn:"咨询"},
    {en:"consume",cn:"消耗"},{en:"consumer",cn:"消费者"},{en:"contact",cn:"接触"},{en:"contain",cn:"包含"},
    {en:"contemporary",cn:"当代的"},{en:"content",cn:"内容"},{en:"contest",cn:"竞赛"},{en:"context",cn:"上下文"},
    {en:"continent",cn:"大陆"},{en:"continue",cn:"继续"},{en:"contract",cn:"合同"},{en:"contrary",cn:"相反的"},
    {en:"contrast",cn:"对比"},{en:"contribute",cn:"贡献"},{en:"control",cn:"控制"},{en:"controversial",cn:"有争议的"},
    {en:"convenient",cn:"方便的"},{en:"convention",cn:"大会"},{en:"conventional",cn:"传统的"},{en:"conversation",cn:"对话"},
    {en:"convince",cn:"说服"},{en:"cook",cn:"烹饪"},{en:"cool",cn:"凉爽的"},{en:"cooperate",cn:"合作"},
    {en:"cope",cn:"应对"},{en:"copy",cn:"复制"},{en:"core",cn:"核心"},{en:"corn",cn:"玉米"},
    {en:"corner",cn:"角落"},{en:"corporate",cn:"公司的"},{en:"correct",cn:"正确的"},{en:"correspond",cn:"对应"},
    {en:"cost",cn:"成本"},{en:"costly",cn:"昂贵的"},{en:"cottage",cn:"小屋"},{en:"cotton",cn:"棉花"},
    {en:"council",cn:"委员会"},{en:"count",cn:"计数"},{en:"counter",cn:"柜台"},{en:"country",cn:"国家"},
    {en:"countryside",cn:"农村"},{en:"county",cn:"县"},{en:"couple",cn:"一对"},{en:"courage",cn:"勇气"},
    {en:"course",cn:"课程"},{en:"court",cn:"法庭"},{en:"cousin",cn:"表亲"},{en:"cover",cn:"覆盖"},
    {en:"crack",cn:"裂缝"},{en:"craft",cn:"工艺"},{en:"crash",cn:"碰撞"},{en:"crazy",cn:"疯狂的"},
    {en:"cream",cn:"奶油"},{en:"create",cn:"创造"},{en:"creative",cn:"创造性的"},{en:"creature",cn:"生物"},
    {en:"credit",cn:"信用"},{en:"crew",cn:"船员"},{en:"crime",cn:"犯罪"},{en:"criminal",cn:"犯罪的"},
    {en:"crisis",cn:"危机"},{en:"critical",cn:"关键的"},{en:"criticism",cn:"批评"},{en:"crop",cn:"庄稼"},
    {en:"cross",cn:"穿过"},{en:"crowd",cn:"人群"},{en:"crucial",cn:"至关重要的"},{en:"cruel",cn:"残忍的"},
    {en:"crush",cn:"压碎"},{en:"cry",cn:"哭"},{en:"cultivate",cn:"培养"},{en:"culture",cn:"文化"},
    {en:"cup",cn:"杯子"},{en:"cure",cn:"治愈"},{en:"curious",cn:"好奇的"},{en:"currency",cn:"货币"},
    {en:"current",cn:"当前的"},{en:"curriculum",cn:"课程"},{en:"custom",cn:"习俗"},{en:"customer",cn:"顾客"},
    {en:"cut",cn:"切"},{en:"cycle",cn:"循环"},{en:"daily",cn:"每日的"},{en:"damage",cn:"损害"},
    {en:"damp",cn:"潮湿的"},{en:"dance",cn:"跳舞"},{en:"danger",cn:"危险"},{en:"dangerous",cn:"危险的"},
    {en:"dare",cn:"敢"},{en:"dark",cn:"黑暗的"},{en:"data",cn:"数据"},{en:"date",cn:"日期"},
    {en:"daughter",cn:"女儿"},{en:"dawn",cn:"黎明"},{en:"day",cn:"天"},{en:"dead",cn:"死的"},
    {en:"deal",cn:"处理"},{en:"dear",cn:"亲爱的"},{en:"death",cn:"死亡"},{en:"debate",cn:"辩论"},
    {en:"debt",cn:"债务"},{en:"decade",cn:"十年"},{en:"deceive",cn:"欺骗"},{en:"decide",cn:"决定"},
    {en:"decision",cn:"决定"},{en:"declare",cn:"宣布"},{en:"decline",cn:"下降"},{en:"decorate",cn:"装饰"},
    {en:"decrease",cn:"减少"},{en:"deed",cn:"行为"},{en:"deep",cn:"深的"},{en:"defeat",cn:"击败"},
    {en:"defend",cn:"防御"},{en:"define",cn:"定义"},{en:"definite",cn:"明确的"},{en:"definition",cn:"定义"},
    {en:"degree",cn:"程度"},{en:"delay",cn:"延迟"},{en:"deliberate",cn:"故意的"},{en:"delicate",cn:"精致的"},
    {en:"delicious",cn:"美味的"},{en:"deliver",cn:"交付"},{en:"delivery",cn:"交付"},{en:"demand",cn:"需求"},
    {en:"democracy",cn:"民主"},{en:"demonstrate",cn:"演示"},{en:"deny",cn:"否认"},{en:"depart",cn:"离开"},
    {en:"department",cn:"部门"},{en:"depend",cn:"依赖"},{en:"deposit",cn:"存款"},{en:"depress",cn:"使沮丧"},
    {en:"depression",cn:"抑郁"},{en:"derive",cn:"源自"},{en:"describe",cn:"描述"},{en:"description",cn:"描述"},
    {en:"desert",cn:"沙漠"},{en:"deserve",cn:"值得"},{en:"design",cn:"设计"},{en:"desire",cn:"渴望"},
    {en:"desk",cn:"书桌"},{en:"desperate",cn:"绝望的"},{en:"despite",cn:"尽管"},{en:"destination",cn:"目的地"},
    {en:"destroy",cn:"摧毁"},{en:"destruction",cn:"破坏"},{en:"detail",cn:"细节"},{en:"detect",cn:"检测"},
    {en:"determine",cn:"确定"},{en:"develop",cn:"发展"},{en:"development",cn:"发展"},{en:"device",cn:"设备"},
    {en:"devote",cn:"奉献"},{en:"dialog",cn:"对话"},{en:"diamond",cn:"钻石"},{en:"diary",cn:"日记"},
    {en:"dictionary",cn:"字典"},{en:"die",cn:"死"},{en:"diet",cn:"饮食"},{en:"differ",cn:"不同"},
    {en:"difference",cn:"差异"},{en:"different",cn:"不同的"},{en:"difficult",cn:"困难的"},{en:"difficulty",cn:"困难"},
    {en:"dig",cn:"挖"},{en:"digest",cn:"消化"},{en:"digital",cn:"数字的"},{en:"dilemma",cn:"困境"},
    {en:"dimension",cn:"维度"},{en:"dinner",cn:"晚餐"},{en:"direct",cn:"直接的"},{en:"direction",cn:"方向"},
    {en:"director",cn:"导演"},{en:"dirty",cn:"脏的"},{en:"disability",cn:"残疾"},{en:"disadvantage",cn:"缺点"},
    {en:"disagree",cn:"不同意"},{en:"disappear",cn:"消失"},{en:"disappoint",cn:"使失望"},{en:"disaster",cn:"灾难"},
    {en:"discipline",cn:"纪律"},{en:"discount",cn:"折扣"},{en:"discover",cn:"发现"},{en:"discovery",cn:"发现"},
    {en:"discuss",cn:"讨论"},{en:"discussion",cn:"讨论"},{en:"disease",cn:"疾病"},{en:"dish",cn:"盘子"},
    {en:"dismiss",cn:"解雇"},{en:"disorder",cn:"混乱"},{en:"display",cn:"展示"},{en:"distance",cn:"距离"},
    {en:"distant",cn:"遥远的"},{en:"distinct",cn:"不同的"},{en:"distinguish",cn:"区分"},{en:"distribute",cn:"分配"},
    {en:"distribution",cn:"分配"},{en:"district",cn:"区"},{en:"disturb",cn:"打扰"},{en:"divide",cn:"划分"},
    {en:"division",cn:"部门"},{en:"divorce",cn:"离婚"},{en:"document",cn:"文件"},{en:"dog",cn:"狗"},
    {en:"dollar",cn:"美元"},{en:"domestic",cn:"国内的"},{en:"dominant",cn:"主导的"},{en:"dominate",cn:"主导"},
    {en:"door",cn:"门"},{en:"double",cn:"双倍"},{en:"doubt",cn:"怀疑"},{en:"down",cn:"向下"},
    {en:"download",cn:"下载"},{en:"downtown",cn:"市中心"},{en:"dozen",cn:"一打"},{en:"draft",cn:"草案"},
    {en:"drag",cn:"拖"},{en:"drama",cn:"戏剧"},{en:"dramatic",cn:"戏剧性的"},{en:"draw",cn:"画"},
    {en:"drawer",cn:"抽屉"},{en:"dream",cn:"梦"},{en:"dress",cn:"连衣裙"},{en:"drink",cn:"喝"},
    {en:"drive",cn:"驾驶"},{en:"driver",cn:"司机"},{en:"drop",cn:"掉落"},{en:"drown",cn:"淹死"},
    {en:"drug",cn:"药物"},{en:"drum",cn:"鼓"},{en:"drunk",cn:"醉的"},{en:"dry",cn:"干燥的"},
    {en:"due",cn:"到期的"},{en:"dull",cn:"无聊的"},{en:"dump",cn:"倾倒"},{en:"during",cn:"在...期间"},
    {en:"dust",cn:"灰尘"},{en:"duty",cn:"职责"},{en:"dynamic",cn:"动态的"},{en:"each",cn:"每个"},
    {en:"eager",cn:"渴望的"},{en:"ear",cn:"耳朵"},{en:"early",cn:"早的"},{en:"earn",cn:"赚"},
    {en:"earth",cn:"地球"},{en:"ease",cn:"轻松"},{en:"easily",cn:"容易地"},{en:"east",cn:"东"},
    {en:"eastern",cn:"东方的"},{en:"easy",cn:"容易的"},{en:"eat",cn:"吃"},{en:"economic",cn:"经济的"},
    {en:"economy",cn:"经济"},{en:"edge",cn:"边缘"},{en:"edition",cn:"版本"},{en:"editor",cn:"编辑"},
    {en:"educate",cn:"教育"},{en:"education",cn:"教育"},{en:"effect",cn:"效果"},{en:"effective",cn:"有效的"},
    {en:"efficient",cn:"高效的"},{en:"effort",cn:"努力"},{en:"egg",cn:"鸡蛋"},{en:"eight",cn:"八"},
    {en:"either",cn:"任一"},{en:"elder",cn:"年长的"},{en:"elect",cn:"选举"},{en:"election",cn:"选举"},
    {en:"electric",cn:"电的"},{en:"electricity",cn:"电"},{en:"electronic",cn:"电子的"},{en:"element",cn:"元素"},
    {en:"eliminate",cn:"消除"},{en:"else",cn:"其他"},{en:"elsewhere",cn:"别处"},{en:"email",cn:"电子邮件"},
    {en:"embrace",cn:"拥抱"},{en:"emerge",cn:"出现"},{en:"emergency",cn:"紧急情况"},{en:"emotion",cn:"情感"},
    {en:"emotional",cn:"情感的"},{en:"emphasis",cn:"强调"},{en:"emphasize",cn:"强调"},{en:"empire",cn:"帝国"},
    {en:"employ",cn:"雇用"},{en:"employee",cn:"雇员"},{en:"employer",cn:"雇主"},{en:"employment",cn:"就业"},
    {en:"empty",cn:"空的"},{en:"enable",cn:"使能够"},{en:"encounter",cn:"遇到"},{en:"encourage",cn:"鼓励"},
    {en:"end",cn:"结束"},{en:"enemy",cn:"敌人"},{en:"energy",cn:"能量"},{en:"engage",cn:"参与"},
    {en:"engine",cn:"引擎"},{en:"engineer",cn:"工程师"},{en:"engineering",cn:"工程"},{en:"enjoy",cn:"享受"},
    {en:"enormous",cn:"巨大的"},{en:"enough",cn:"足够"},{en:"ensure",cn:"确保"},{en:"enter",cn:"进入"},
    {en:"enterprise",cn:"企业"},{en:"entertainment",cn:"娱乐"},{en:"enthusiasm",cn:"热情"},{en:"entire",cn:"整个"},
    {en:"entrance",cn:"入口"},{en:"entry",cn:"条目"},{en:"environment",cn:"环境"},{en:"environmental",cn:"环境的"},
    {en:"equal",cn:"平等的"},{en:"equipment",cn:"设备"},{en:"equivalent",cn:"等价的"},{en:"error",cn:"错误"},
    {en:"escape",cn:"逃跑"},{en:"especially",cn:"特别"},{en:"essay",cn:"论文"},{en:"essential",cn:"必要的"},
    {en:"establish",cn:"建立"},{en:"estimate",cn:"估计"},{en:"evaluate",cn:"评估"},{en:"even",cn:"甚至"},
    {en:"evening",cn:"晚上"},{en:"event",cn:"事件"},{en:"eventually",cn:"最终"},{en:"ever",cn:"曾经"},
    {en:"every",cn:"每个"},{en:"everybody",cn:"每个人"},{en:"everyday",cn:"日常的"},{en:"everyone",cn:"每个人"},
    {en:"everything",cn:"一切"},{en:"everywhere",cn:"到处"},{en:"evidence",cn:"证据"},{en:"evil",cn:"邪恶的"},
    {en:"evolution",cn:"进化"},{en:"evolve",cn:"进化"},{en:"exact",cn:"确切的"},{en:"examination",cn:"考试"},
    {en:"examine",cn:"检查"},{en:"example",cn:"例子"},{en:"excellent",cn:"优秀的"},{en:"except",cn:"除了"},
    {en:"exchange",cn:"交换"},{en:"excite",cn:"使兴奋"},{en:"exciting",cn:"令人兴奋的"},{en:"exclude",cn:"排除"},
    {en:"excuse",cn:"借口"},{en:"exercise",cn:"锻炼"},{en:"exist",cn:"存在"},{en:"existence",cn:"存在"},
    {en:"expand",cn:"扩展"},{en:"expect",cn:"期望"},{en:"expense",cn:"费用"},{en:"expensive",cn:"昂贵的"},
    {en:"experience",cn:"经验"},{en:"experiment",cn:"实验"},{en:"expert",cn:"专家"},{en:"explain",cn:"解释"},
    {en:"explanation",cn:"解释"},{en:"explicit",cn:"明确的"},{en:"explode",cn:"爆炸"},{en:"explore",cn:"探索"},
    {en:"explosion",cn:"爆炸"},{en:"export",cn:"出口"},{en:"expose",cn:"暴露"},{en:"express",cn:"表达"},
    {en:"expression",cn:"表达"},{en:"extend",cn:"延伸"},{en:"extension",cn:"扩展"},{en:"extensive",cn:"广泛的"},
    {en:"extent",cn:"程度"},{en:"external",cn:"外部的"},{en:"extra",cn:"额外的"},{en:"extraordinary",cn:"非凡的"},
    {en:"extreme",cn:"极端的"},{en:"eye",cn:"眼睛"},{en:"face",cn:"脸"},{en:"facility",cn:"设施"},
    {en:"fact",cn:"事实"},{en:"factor",cn:"因素"},{en:"factory",cn:"工厂"},{en:"fade",cn:"褪色"},
    {en:"fail",cn:"失败"},{en:"failure",cn:"失败"},{en:"fair",cn:"公平的"},{en:"faith",cn:"信念"},
    {en:"fall",cn:"落下"},{en:"false",cn:"假的"},{en:"familiar",cn:"熟悉的"},{en:"family",cn:"家庭"},
    {en:"famous",cn:"著名的"},{en:"fan",cn:"粉丝"},{en:"fancy",cn:"花哨的"},{en:"far",cn:"远的"},
    {en:"farm",cn:"农场"},{en:"farmer",cn:"农民"},{en:"fashion",cn:"时尚"},{en:"fast",cn:"快的"},
    {en:"fat",cn:"胖的"},{en:"fatal",cn:"致命的"},{en:"fate",cn:"命运"},{en:"father",cn:"父亲"},
    {en:"fault",cn:"过错"},{en:"favor",cn:"赞成"},{en:"favorite",cn:"最喜欢的"},{en:"fear",cn:"恐惧"},
    {en:"feature",cn:"特征"},{en:"federal",cn:"联邦的"},{en:"fee",cn:"费用"},{en:"feed",cn:"喂养"},
    {en:"feel",cn:"感觉"},{en:"feeling",cn:"感觉"},{en:"fellow",cn:"家伙"},{en:"female",cn:"女性"},
    {en:"fence",cn:"围栏"},{en:"festival",cn:"节日"},{en:"fetch",cn:"取来"},{en:"fever",cn:"发烧"},
    {en:"few",cn:"少数"},{en:"fiber",cn:"纤维"},{en:"field",cn:"领域"},{en:"fierce",cn:"激烈的"},
    {en:"fight",cn:"战斗"},{en:"figure",cn:"人物"},{en:"file",cn:"文件"},{en:"fill",cn:"填满"},
    {en:"film",cn:"电影"},{en:"final",cn:"最终的"},{en:"finance",cn:"金融"},{en:"financial",cn:"金融的"},
    {en:"find",cn:"找到"},{en:"finding",cn:"发现"},{en:"fine",cn:"好的"},{en:"finger",cn:"手指"},
    {en:"finish",cn:"完成"},{en:"fire",cn:"火"},{en:"firm",cn:"公司"},{en:"fish",cn:"鱼"},
    {en:"fit",cn:"适合"},{en:"fix",cn:"修理"},{en:"flag",cn:"旗帜"},{en:"flame",cn:"火焰"},
    {en:"flash",cn:"闪光"},{en:"flat",cn:"平坦的"},{en:"flavor",cn:"味道"},{en:"flesh",cn:"肉"},
    {en:"flight",cn:"航班"},{en:"float",cn:"漂浮"},{en:"flood",cn:"洪水"},{en:"floor",cn:"地板"},
    {en:"flour",cn:"面粉"},{en:"flow",cn:"流动"},{en:"flower",cn:"花"},{en:"flu",cn:"流感"},
    {en:"fly",cn:"飞"},{en:"focus",cn:"焦点"},{en:"fold",cn:"折叠"},{en:"folk",cn:"人们"},
    {en:"follow",cn:"跟随"},{en:"following",cn:"以下的"},{en:"food",cn:"食物"},{en:"fool",cn:"傻瓜"},
    {en:"foot",cn:"脚"},{en:"football",cn:"足球"},{en:"forbid",cn:"禁止"},{en:"force",cn:"力量"},
    {en:"foreign",cn:"外国的"},{en:"forest",cn:"森林"},{en:"forever",cn:"永远"},{en:"forget",cn:"忘记"},
    {en:"forgive",cn:"原谅"},{en:"fork",cn:"叉子"},{en:"form",cn:"形式"},{en:"formal",cn:"正式的"},
    {en:"former",cn:"以前的"},{en:"formula",cn:"公式"},{en:"forth",cn:"向前"},{en:"fortune",cn:"财富"},
    {en:"forward",cn:"向前"},{en:"found",cn:" founded"},{en:"foundation",cn:"基础"},{en:"frame",cn:"框架"},
    {en:"framework",cn:"框架"},{en:"free",cn:"免费的"},{en:"freedom",cn:"自由"},{en:"freeze",cn:"冻结"},
    {en:"frequency",cn:"频率"},{en:"frequent",cn:"频繁的"},{en:"fresh",cn:"新鲜的"},{en:"friend",cn:"朋友"},
    {en:"friendly",cn:"友好的"},{en:"friendship",cn:"友谊"},{en:"frighten",cn:"使害怕"},{en:"front",cn:"前面"},
    {en:"fruit",cn:"水果"},{en:"frustrate",cn:"挫败"},{en:"fuel",cn:"燃料"},{en:"fulfill",cn:"实现"},
    {en:"full",cn:"满的"},{en:"fun",cn:"乐趣"},{en:"function",cn:"功能"},{en:"fund",cn:"基金"},
    {en:"fundamental",cn:"基本的"},{en:"funny",cn:"有趣的"},{en:"furniture",cn:"家具"},{en:"future",cn:"未来"},
  ],
// Level 2: CET-6 六级词汇
  2: [
    {en:"abnormal",cn:"异常的"},{en:"abolish",cn:"废除"},{en:"abrupt",cn:"突然的"},{en:"absence",cn:"缺席"},
    {en:"absent",cn:"缺席的"},{en:"absorb",cn:"吸收"},{en:"abstract",cn:"抽象的"},{en:"absurd",cn:"荒谬的"},
    {en:"abundance",cn:"丰富"},{en:"abundant",cn:"丰富的"},{en:"abuse",cn:"滥用"},{en:"academic",cn:"学术的"},
    {en:"accelerate",cn:"加速"},{en:"access",cn:"访问"},{en:"accommodate",cn:"容纳"},{en:"accomplish",cn:"完成"},
    {en:"accord",cn:"一致"},{en:"account",cn:"账户"},{en:"accumulate",cn:"积累"},{en:"accurate",cn:"精确的"},
    {en:"accuse",cn:"指控"},{en:"accustom",cn:"使习惯"},{en:"achieve",cn:"实现"},{en:"acknowledge",cn:"承认"},
    {en:"acquaint",cn:"使了解"},{en:"acquire",cn:"获得"},{en:"activate",cn:"激活"},{en:"acute",cn:"急性的"},
    {en:"adapt",cn:"适应"},{en:"addict",cn:"使上瘾"},{en:"adequate",cn:"足够的"},{en:"adhere",cn:"坚持"},
    {en:"adjacent",cn:"邻近的"},{en:"adjust",cn:"调整"},{en:"administer",cn:"管理"},{en:"admire",cn:"钦佩"},
    {en:"admit",cn:"承认"},{en:"adolescent",cn:"青少年"},{en:"adopt",cn:"采用"},{en:"advance",cn:"前进"},
    {en:"advantage",cn:"优势"},{en:"adventure",cn:"冒险"},{en:"adverse",cn:"不利的"},{en:"advertise",cn:"做广告"},
    {en:"advocate",cn:"提倡"},{en:"aesthetic",cn:"审美的"},{en:"affect",cn:"影响"},{en:"affection",cn:"感情"},
    {en:"affiliate",cn:"附属"},{en:"affirm",cn:"肯定"},{en:"afford",cn:"负担得起"},{en:"agenda",cn:"议程"},
    {en:"aggravate",cn:"加重"},{en:"aggregate",cn:"总计"},{en:"aggressive",cn:"侵略性的"},{en:"agitate",cn:"煽动"},
    {en:"alert",cn:"警觉的"},{en:"alien",cn:"外星的"},{en:"align",cn:"对齐"},{en:"allege",cn:"声称"},
    {en:"alleviate",cn:"减轻"},{en:"alliance",cn:"联盟"},{en:"allocate",cn:"分配"},{en:"allow",cn:"允许"},
    {en:"allowance",cn:"津贴"},{en:"ally",cn:"盟友"},{en:"alongside",cn:"在旁边"},{en:"alter",cn:"改变"},
    {en:"alternative",cn:"替代的"},{en:"altitude",cn:"高度"},{en:"altogether",cn:"完全"},{en:"amateur",cn:"业余的"},
    {en:"ambiguous",cn:"模棱两可的"},{en:"ambition",cn:"野心"},{en:"amend",cn:"修正"},{en:"ample",cn:"充足的"},
    {en:"amplify",cn:"放大"},{en:"analogy",cn:"类比"},{en:"analyse",cn:"分析"},{en:"ancestor",cn:"祖先"},
    {en:"anchor",cn:"锚"},{en:"ancient",cn:"古代的"},{en:"announce",cn:"宣布"},{en:"annual",cn:"年度的"},
    {en:"anonymous",cn:"匿名的"},{en:"anticipate",cn:"预期"},{en:"anxiety",cn:"焦虑"},{en:"apparatus",cn:"装置"},
    {en:"apparent",cn:"明显的"},{en:"appeal",cn:"呼吁"},{en:"appetite",cn:"食欲"},{en:"applaud",cn:"鼓掌"},
    {en:"appliance",cn:"电器"},{en:"applicable",cn:"适用的"},{en:"applicant",cn:"申请人"},{en:"application",cn:"申请"},
    {en:"appoint",cn:"任命"},{en:"appraise",cn:"评估"},{en:"appreciate",cn:"感激"},{en:"apprehend",cn:"逮捕"},
    {en:"approach",cn:"接近"},{en:"appropriate",cn:"适当的"},{en:"approve",cn:"批准"},{en:"apt",cn:"恰当的"},
    {en:"arbitrary",cn:"任意的"},{en:"arise",cn:"出现"},{en:"arouse",cn:"唤起"},{en:"arrange",cn:"安排"},
    {en:"array",cn:"数组"},{en:"arrest",cn:"逮捕"},{en:"articulate",cn:"清晰表达"},{en:"artificial",cn:"人工的"},
    {en:"ascend",cn:"上升"},{en:"ascertain",cn:"确定"},{en:"aspect",cn:"方面"},{en:"aspire",cn:"渴望"},
    {en:"assault",cn:"攻击"},{en:"assemble",cn:"组装"},{en:"assert",cn:"断言"},{en:"assess",cn:"评估"},
    {en:"asset",cn:"资产"},{en:"assign",cn:"分配"},{en:"assist",cn:"协助"},{en:"associate",cn:"联系"},
    {en:"assume",cn:"假设"},{en:"assure",cn:"保证"},{en:"asylum",cn:"庇护所"},{en:"atmosphere",cn:"气氛"},
    {en:"attach",cn:"附上"},{en:"attain",cn:"达到"},{en:"attempt",cn:"尝试"},{en:"attend",cn:"参加"},
    {en:"attitude",cn:"态度"},{en:"attorney",cn:"律师"},{en:"attract",cn:"吸引"},{en:"attribute",cn:"属性"},
    {en:"authentic",cn:"真实的"},{en:"authority",cn:"权威"},{en:"authorize",cn:"授权"},{en:"automatic",cn:"自动的"},
    {en:"autonomy",cn:"自治"},{en:"available",cn:"可用的"},{en:"avert",cn:"避免"},{en:"avoid",cn:"避免"},
    {en:"award",cn:"奖"},{en:"aware",cn:"意识到的"},{en:"awful",cn:"糟糕的"},{en:"awkward",cn:"尴尬的"},
    {en:"bachelor",cn:"学士"},{en:"backward",cn:"向后的"},{en:"baffle",cn:"使困惑"},{en:"balance",cn:"平衡"},
    {en:"ban",cn:"禁止"},{en:"band",cn:"乐队"},{en:"bankrupt",cn:"破产的"},{en:"banner",cn:"横幅"},
    {en:"bare",cn:"裸露的"},{en:"barely",cn:"几乎不"},{en:"bargain",cn:"便宜货"},{en:"barrier",cn:"障碍"},
    {en:"basic",cn:"基本的"},{en:"basis",cn:"基础"},{en:"batch",cn:"批次"},{en:"beam",cn:"光束"},
    {en:"bear",cn:"承受"},{en:"behalf",cn:"代表"},{en:"behave",cn:"行为"},{en:"being",cn:"存在"},
    {en:"benefit",cn:"利益"},{en:"benign",cn:"良性的"},{en:"besides",cn:"此外"},{en:"betray",cn:"背叛"},
    {en:"bias",cn:"偏见"},{en:"bid",cn:"出价"},{en:"bind",cn:"绑"},{en:"biology",cn:"生物学"},
    {en:"bizarre",cn:"奇异的"},{en:"blade",cn:"刀片"},{en:"blame",cn:"责备"},{en:"blank",cn:"空白的"},
    {en:"blast",cn:"爆炸"},{en:"blaze",cn:"火焰"},{en:"bleed",cn:"流血"},{en:"blend",cn:"混合"},
    {en:"bless",cn:"祝福"},{en:"block",cn:"阻塞"},{en:"bloody",cn:"血腥的"},{en:"bloom",cn:"开花"},
    {en:"blunder",cn:"大错"},{en:"board",cn:"板"},{en:"boast",cn:"吹嘘"},{en:"bold",cn:"大胆的"},
    {en:"bolt",cn:"螺栓"},{en:"bomb",cn:"炸弹"},{en:"bond",cn:"纽带"},{en:"boost",cn:"促进"},
    {en:"border",cn:"边界"},{en:"bore",cn:"使无聊"},{en:"bother",cn:"打扰"},{en:"bounce",cn:"弹跳"},
    {en:"bound",cn:"一定的"},{en:"boundary",cn:"边界"},{en:"branch",cn:"分支"},{en:"brand",cn:"品牌"},
    {en:"breakdown",cn:"故障"},{en:"breakthrough",cn:"突破"},{en:"breed",cn:"品种"},{en:"breeze",cn:"微风"},
    {en:"brief",cn:"简短的"},{en:"brilliant",cn:"辉煌的"},{en:"brisk",cn:"轻快的"},{en:"broadcast",cn:"广播"},
    {en:"brochure",cn:"小册子"},{en:"browse",cn:"浏览"},{en:"bruise",cn:"瘀伤"},{en:"brush",cn:"刷子"},
    {en:"budget",cn:"预算"},{en:"bulk",cn:"大量"},{en:"bullet",cn:"子弹"},{en:"bump",cn:"碰撞"},
    {en:"bunch",cn:"束"},{en:"burden",cn:"负担"},{en:"bureau",cn:"局"},{en:"bureaucracy",cn:"官僚主义"},
    {en:"burst",cn:"爆发"},{en:"cabin",cn:"小屋"},{en:"cabinet",cn:"内阁"},{en:"calculate",cn:"计算"},
    {en:"campaign",cn:"运动"},{en:"cancel",cn:"取消"},{en:"candidate",cn:"候选人"},{en:"capable",cn:"有能力的"},
    {en:"capacity",cn:"容量"},{en:"capital",cn:"首都"},{en:"capture",cn:"捕获"},{en:"carbon",cn:"碳"},
    {en:"career",cn:"职业"},{en:"cargo",cn:"货物"},{en:"carriage",cn:"马车"},{en:"cascade",cn:"级联"},
    {en:"casual",cn:"随意的"},{en:"casualty",cn:"伤亡"},{en:"catalog",cn:"目录"},{en:"catastrophe",cn:"灾难"},
    {en:"category",cn:"类别"},{en:"cater",cn:"迎合"},{en:"cease",cn:"停止"},{en:"celebrate",cn:"庆祝"},
    {en:"censor",cn:"审查"},{en:"ceremony",cn:"仪式"},{en:"certificate",cn:"证书"},{en:"chain",cn:"链"},
    {en:"challenge",cn:"挑战"},{en:"champion",cn:"冠军"},{en:"channel",cn:"频道"},{en:"chapter",cn:"章节"},
    {en:"character",cn:"角色"},{en:"charge",cn:"收费"},{en:"charity",cn:"慈善"},{en:"charm",cn:"魅力"},
    {en:"charter",cn:"宪章"},{en:"chase",cn:"追逐"},{en:"cheat",cn:"作弊"},{en:"check",cn:"检查"},
    {en:"chemical",cn:"化学的"},{en:"cherish",cn:"珍惜"},{en:"chief",cn:"主要的"},{en:"chronic",cn:"慢性的"},
    {en:"circulate",cn:"循环"},{en:"circumstance",cn:"情况"},{en:"cite",cn:"引用"},{en:"civil",cn:"民事的"},
    {en:"civilian",cn:"平民"},{en:"claim",cn:"声称"},{en:"clarify",cn:"澄清"},{en:"clash",cn:"冲突"},
    {en:"classic",cn:"经典的"},{en:"classify",cn:"分类"},{en:"clause",cn:"条款"},{en:"clay",cn:"粘土"},
    {en:"click",cn:"点击"},{en:"client",cn:"客户"},{en:"climate",cn:"气候"},{en:"cling",cn:"紧贴"},
    {en:"clinical",cn:"临床的"},{en:"clip",cn:"夹子"},{en:"clone",cn:"克隆"},{en:"clue",cn:"线索"},
    {en:"cluster",cn:"集群"},{en:"coalition",cn:"联盟"},{en:"code",cn:"代码"},{en:"cognitive",cn:"认知的"},
    {en:"coherent",cn:"连贯的"},{en:"coincide",cn:"巧合"},{en:"collaborate",cn:"合作"},{en:"collapse",cn:"倒塌"},
    {en:"colleague",cn:"同事"},{en:"collect",cn:"收集"},{en:"collision",cn:"碰撞"},{en:"colony",cn:"殖民地"},
    {en:"column",cn:"栏"},{en:"combat",cn:"战斗"},{en:"combine",cn:"结合"},{en:"command",cn:"命令"},
    {en:"commemorate",cn:"纪念"},{en:"commence",cn:"开始"},{en:"commend",cn:"表扬"},{en:"comment",cn:"评论"},
    {en:"commercial",cn:"商业的"},{en:"commission",cn:"委员会"},{en:"commit",cn:"犯；承诺"},{en:"committee",cn:"委员会"},
    {en:"commodity",cn:"商品"},{en:"common",cn:"共同的"},{en:"communicate",cn:"沟通"},{en:"community",cn:"社区"},
    {en:"compact",cn:"紧凑的"},{en:"companion",cn:"同伴"},{en:"company",cn:"公司"},{en:"comparable",cn:"可比较的"},
    {en:"comparative",cn:"比较的"},{en:"compare",cn:"比较"},{en:"comparison",cn:"比较"},{en:"compel",cn:"强迫"},
    {en:"compensate",cn:"补偿"},{en:"compete",cn:"竞争"},{en:"competent",cn:"有能力的"},{en:"competition",cn:"竞争"},
    {en:"compile",cn:"编译"},{en:"complain",cn:"抱怨"},{en:"complement",cn:"补充"},{en:"complete",cn:"完成"},
    {en:"complex",cn:"复杂的"},{en:"comply",cn:"遵守"},{en:"component",cn:"组件"},{en:"compose",cn:"组成"},
    {en:"compound",cn:"化合物"},{en:"comprehend",cn:"理解"},{en:"comprehensive",cn:"全面的"},{en:"compress",cn:"压缩"},
    {en:"comprise",cn:"包含"},{en:"compromise",cn:"妥协"},{en:"compulsory",cn:"强制的"},{en:"compute",cn:"计算"},
    {en:"conceal",cn:"隐藏"},{en:"concede",cn:"承认"},{en:"conceive",cn:"构想"},{en:"concentrate",cn:"集中"},
    {en:"concept",cn:"概念"},{en:"concern",cn:"关心"},{en:"conclude",cn:"总结"},{en:"concrete",cn:"具体的"},
    {en:"condemn",cn:"谴责"},{en:"conduct",cn:"进行"},{en:"conference",cn:"会议"},{en:"confess",cn:"承认"},
    {en:"confidence",cn:"信心"},{en:"confine",cn:"限制"},{en:"confirm",cn:"确认"},{en:"conflict",cn:"冲突"},
    {en:"conform",cn:"遵守"},{en:"confront",cn:"面对"},{en:"confuse",cn:"困惑"},{en:"congregate",cn:"聚集"},
    {en:"congress",cn:"国会"},{en:"connect",cn:"连接"},{en:"conquest",cn:"征服"},{en:"conscience",cn:"良心"},
    {en:"conscious",cn:"有意识的"},{en:"consensus",cn:"共识"},{en:"consent",cn:"同意"},{en:"consequence",cn:"后果"},
    {en:"consequent",cn:"随之发生的"},{en:"conserve",cn:"保存"},{en:"conservative",cn:"保守的"},{en:"consider",cn:"考虑"},
    {en:"considerable",cn:"相当大的"},{en:"consist",cn:"由...组成"},{en:"consistent",cn:"一致的"},{en:"consolidate",cn:"巩固"},
    {en:"conspiracy",cn:"阴谋"},{en:"constant",cn:"恒定的"},{en:"constitute",cn:"构成"},{en:"constitution",cn:"宪法"},
    {en:"constrain",cn:"约束"},{en:"construct",cn:"建造"},{en:"consult",cn:"咨询"},{en:"consume",cn:"消耗"},
    {en:"contact",cn:"接触"},{en:"contain",cn:"包含"},{en:"contaminate",cn:"污染"},{en:"contemplate",cn:"沉思"},
    {en:"contemporary",cn:"当代的"},{en:"contempt",cn:"蔑视"},{en:"contend",cn:"竞争"},{en:"content",cn:"内容"},
    {en:"contest",cn:"竞赛"},{en:"context",cn:"上下文"},{en:"continent",cn:"大陆"},{en:"contingent",cn:"视情况而定的"},
    {en:"contract",cn:"合同"},{en:"contradict",cn:"矛盾"},{en:"contrary",cn:"相反的"},{en:"contrast",cn:"对比"},
    {en:"contribute",cn:"贡献"},{en:"control",cn:"控制"},{en:"controversial",cn:"有争议的"},{en:"controversy",cn:"争论"},
    {en:"convene",cn:"召集"},{en:"convention",cn:"大会"},{en:"converge",cn:"汇聚"},{en:"conversation",cn:"对话"},
    {en:"convert",cn:"转换"},{en:"convey",cn:"传达"},{en:"convict",cn:"定罪"},{en:"convince",cn:"说服"},
    {en:"cooperate",cn:"合作"},{en:"cooperative",cn:"合作的"},{en:"coordinate",cn:"协调"},{en:"cope",cn:"应对"},
    {en:"core",cn:"核心"},{en:"corporate",cn:"公司的"},{en:"correlate",cn:"相关"},{en:"correspond",cn:"对应"},
    {en:"correspondent",cn:"记者"},{en:"corrode",cn:"腐蚀"},{en:"corrupt",cn:"腐败的"},{en:"costly",cn:"昂贵的"},
    {en:"council",cn:"委员会"},{en:"count",cn:"计数"},{en:"counterpart",cn:"对应物"},{en:"county",cn:"县"},
    {en:"coup",cn:"政变"},{en:"couple",cn:"一对"},{en:"courage",cn:"勇气"},{en:"course",cn:"课程"},
    {en:"court",cn:"法庭"},{en:"courtesy",cn:"礼貌"},{en:"coverage",cn:"覆盖范围"},{en:"crack",cn:"裂缝"},
    {en:"craft",cn:"工艺"},{en:"crash",cn:"碰撞"},{en:"create",cn:"创造"},{en:"credential",cn:"资格"},
    {en:"credit",cn:"信用"},{en:"crew",cn:"船员"},{en:"crime",cn:"犯罪"},{en:"criminal",cn:"犯罪的"},
    {en:"cripple",cn:"使残废"},{en:"crisis",cn:"危机"},{en:"criterion",cn:"标准"},{en:"critical",cn:"关键的"},
    {en:"critique",cn:"批评"},{en:"crop",cn:"庄稼"},{en:"crucial",cn:"至关重要的"},{en:"crude",cn:"粗糙的"},
    {en:"crush",cn:"压碎"},{en:"cultivate",cn:"培养"},{en:"culture",cn:"文化"},{en:"cumulative",cn:"累积的"},
    {en:"curb",cn:"抑制"},{en:"currency",cn:"货币"},{en:"current",cn:"当前的"},{en:"curriculum",cn:"课程"},
    {en:"curtail",cn:"削减"},{en:"curve",cn:"曲线"},{en:"custom",cn:"习俗"},{en:"customer",cn:"顾客"},
    {en:"cycle",cn:"循环"},{en:"cynical",cn:"愤世嫉俗的"},{en:"damage",cn:"损害"},{en:"damp",cn:"潮湿的"},
    {en:"dare",cn:"敢"},{en:"data",cn:"数据"},{en:"daunting",cn:"令人畏惧的"},{en:"dawn",cn:"黎明"},
    {en:"dazzle",cn:"使目眩"},{en:"deadline",cn:"截止日期"},{en:"deal",cn:"处理"},{en:"debate",cn:"辩论"},
    {en:"debut",cn:"首次亮相"},{en:"decade",cn:"十年"},{en:"deceive",cn:"欺骗"},{en:"decent",cn:"体面的"},
    {en:"decide",cn:"决定"},{en:"decisive",cn:"决定性的"},{en:"declare",cn:"宣布"},{en:"decline",cn:"下降"},
    {en:"decorate",cn:"装饰"},{en:"decrease",cn:"减少"},{en:"dedicate",cn:"奉献"},{en:"deem",cn:"认为"},
    {en:"deep",cn:"深的"},{en:"default",cn:"默认"},{en:"defeat",cn:"击败"},{en:"defect",cn:"缺陷"},
    {en:"defend",cn:"防御"},{en:"deficit",cn:"赤字"},{en:"define",cn:"定义"},{en:"definite",cn:"明确的"},
    {en:"defy",cn:"违抗"},{en:"degree",cn:"程度"},{en:"delay",cn:"延迟"},{en:"delegate",cn:"委托"},
    {en:"deliberate",cn:"故意的"},{en:"delicate",cn:"精致的"},{en:"deliver",cn:"交付"},{en:"demand",cn:"需求"},
    {en:"democracy",cn:"民主"},{en:"demonstrate",cn:"演示"},{en:"denote",cn:"表示"},{en:"denounce",cn:"谴责"},
    {en:"dense",cn:"密集的"},{en:"deny",cn:"否认"},{en:"depart",cn:"离开"},{en:"department",cn:"部门"},
    {en:"depend",cn:"依赖"},{en:"depict",cn:"描绘"},{en:"deploy",cn:"部署"},{en:"deposit",cn:"存款"},
    {en:"deprive",cn:"剥夺"},{en:"depute",cn:"委派"},{en:"derive",cn:"源自"},{en:"descend",cn:"下降"},
    {en:"describe",cn:"描述"},{en:"desert",cn:"沙漠"},{en:"deserve",cn:"值得"},{en:"design",cn:"设计"},
    {en:"designate",cn:"指定"},{en:"desire",cn:"渴望"},{en:"despair",cn:"绝望"},{en:"desperate",cn:"绝望的"},
    {en:"despite",cn:"尽管"},{en:"destination",cn:"目的地"},{en:"destiny",cn:"命运"},{en:"destroy",cn:"摧毁"},
    {en:"detach",cn:"分离"},{en:"detail",cn:"细节"},{en:"detain",cn:"拘留"},{en:"detect",cn:"检测"},
    {en:"deteriorate",cn:"恶化"},{en:"determine",cn:"确定"},{en:"develop",cn:"发展"},{en:"deviate",cn:"偏离"},
    {en:"device",cn:"设备"},{en:"devise",cn:"设计"},{en:"devote",cn:"奉献"},{en:"diagnose",cn:"诊断"},
    {en:"differ",cn:"不同"},{en:"differentiate",cn:"区分"},{en:"diffuse",cn:"扩散"},{en:"digest",cn:"消化"},
    {en:"dilemma",cn:"困境"},{en:"dimension",cn:"维度"},{en:"diminish",cn:"减少"},{en:"diplomat",cn:"外交官"},
    {en:"direct",cn:"直接的"},{en:"disable",cn:"使残疾"},{en:"disadvantage",cn:"缺点"},{en:"disappoint",cn:"使失望"},
    {en:"disaster",cn:"灾难"},{en:"discipline",cn:"纪律"},{en:"disclose",cn:"披露"},{en:"discount",cn:"折扣"},
    {en:"discourse",cn:"话语"},{en:"discover",cn:"发现"},{en:"discrepancy",cn:"差异"},{en:"discrete",cn:"离散的"},
    {en:"discriminate",cn:"歧视"},{en:"disguise",cn:"伪装"},{en:"dismiss",cn:"解雇"},{en:"disorder",cn:"混乱"},
    {en:"disperse",cn:"分散"},{en:"displace",cn:"取代"},{en:"display",cn:"展示"},{en:"dispose",cn:"处置"},
    {en:"disregard",cn:"无视"},{en:"disrupt",cn:"破坏"},{en:"dissolve",cn:"溶解"},{en:"distinguish",cn:"区分"},
    {en:"distort",cn:"扭曲"},{en:"distract",cn:"分散注意力"},{en:"distress",cn:"苦恼"},{en:"distribute",cn:"分配"},
    {en:"disturb",cn:"打扰"},{en:"diverse",cn:"多样的"},{en:"divert",cn:"转移"},{en:"divide",cn:"划分"},
    {en:"divine",cn:"神圣的"},{en:"document",cn:"文件"},{en:"doctrine",cn:"学说"},{en:"domain",cn:"领域"},
    {en:"domestic",cn:"国内的"},{en:"dominant",cn:"主导的"},{en:"donate",cn:"捐赠"},{en:"donor",cn:"捐赠者"},
    {en:"doom",cn:"厄运"},{en:"dose",cn:"剂量"},{en:"draft",cn:"草案"},{en:"drain",cn:"排水"},
    {en:"dramatic",cn:"戏剧性的"},{en:"drastic",cn:"激烈的"},{en:"dread",cn:"恐惧"},{en:"drift",cn:"漂流"},
    {en:"drought",cn:"干旱"},{en:"drown",cn:"淹死"},{en:"dub",cn:"配音"},{en:"due",cn:"到期的"},
    {en:"dull",cn:"无聊的"},{en:"dump",cn:"倾倒"},{en:"duplicate",cn:"复制"},{en:"durable",cn:"耐用的"},
    {en:"duration",cn:"持续时间"},{en:"dwell",cn:"居住"},{en:"dynamic",cn:"动态的"},{en:"earnest",cn:"认真的"},
    {en:"ease",cn:"轻松"},{en:"eccentric",cn:"古怪的"},{en:"eclipse",cn:"日食"},{en:"ecology",cn:"生态学"},
    {en:"economic",cn:"经济的"},{en:"economy",cn:"经济"},{en:"edge",cn:"边缘"},{en:"edit",cn:"编辑"},
    {en:"edition",cn:"版本"},{en:"editor",cn:"编辑"},{en:"educate",cn:"教育"},{en:"effect",cn:"效果"},
    {en:"effective",cn:"有效的"},{en:"efficient",cn:"高效的"},{en:"effort",cn:"努力"},{en:"elaborate",cn:"精心制作"},
    {en:"elect",cn:"选举"},{en:"election",cn:"选举"},{en:"electric",cn:"电的"},{en:"electronic",cn:"电子的"},
    {en:"elegant",cn:"优雅的"},{en:"element",cn:"元素"},{en:"elevate",cn:"提升"},{en:"eligible",cn:"有资格的"},
    {en:"eliminate",cn:"消除"},{en:"elite",cn:"精英"},{en:"eloquent",cn:"雄辩的"},{en:"embrace",cn:"拥抱"},
    {en:"emerge",cn:"出现"},{en:"emergency",cn:"紧急情况"},{en:"emit",cn:"发出"},{en:"emotion",cn:"情感"},
    {en:"emphasis",cn:"强调"},{en:"emphasize",cn:"强调"},{en:"empirical",cn:"经验的"},{en:"employ",cn:"雇用"},
    {en:"employee",cn:"雇员"},{en:"employment",cn:"就业"},{en:"enable",cn:"使能够"},{en:"encounter",cn:"遇到"},
    {en:"encourage",cn:"鼓励"},{en:"endanger",cn:"危及"},{en:"endeavor",cn:"努力"},{en:"endorse",cn:"赞同"},
    {en:"endure",cn:"忍受"},{en:"enforce",cn:"执行"},{en:"engage",cn:"参与"},{en:"enhance",cn:"增强"},
    {en:"enjoy",cn:"享受"},{en:"enlighten",cn:"启发"},{en:"enormous",cn:"巨大的"},{en:"enrich",cn:"丰富"},
    {en:"enroll",cn:"注册"},{en:"ensure",cn:"确保"},{en:"ensue",cn:"接着发生"},{en:"entail",cn:"需要"},
    {en:"enterprise",cn:"企业"},{en:"enthusiastic",cn:"热情的"},{en:"entire",cn:"整个"},{en:"entity",cn:"实体"},
    {en:"entrepreneur",cn:"企业家"},{en:"envisage",cn:"设想"},{en:"environment",cn:"环境"},{en:"epidemic",cn:"流行病"},
    {en:"equal",cn:"平等的"},{en:"equip",cn:"装备"},{en:"equipment",cn:"设备"},{en:"equivalent",cn:"等价的"},
    {en:"era",cn:"时代"},{en:"erode",cn:"侵蚀"},{en:"error",cn:"错误"},{en:"erupt",cn:"爆发"},
    {en:"escape",cn:"逃跑"},{en:"escort",cn:"护送"},{en:"essence",cn:"本质"},{en:"essential",cn:"必要的"},
    {en:"establish",cn:"建立"},{en:"estate",cn:"房产"},{en:"esteem",cn:"尊重"},{en:"estimate",cn:"估计"},
    {en:"evacuate",cn:"疏散"},{en:"evaluate",cn:"评估"},{en:"evoke",cn:"唤起"},{en:"evolution",cn:"进化"},
    {en:"evolve",cn:"进化"},{en:"exaggerate",cn:"夸大"},{en:"exceed",cn:"超过"},{en:"excel",cn:"擅长"},
    {en:"exception",cn:"例外"},{en:"excerpt",cn:"摘录"},{en:"excess",cn:"过量"},{en:"exchange",cn:"交换"},
    {en:"exclude",cn:"排除"},{en:"exclusive",cn:"排他的"},{en:"execute",cn:"执行"},{en:"exempt",cn:"豁免"},
    {en:"exercise",cn:"锻炼"},{en:"exert",cn:"施加"},{en:"exhaust",cn:"耗尽"},{en:"exhibit",cn:"展览"},
    {en:"exile",cn:"流放"},{en:"exist",cn:"存在"},{en:"expand",cn:"扩展"},{en:"expect",cn:"期望"},
    {en:"expedition",cn:"远征"},{en:"expel",cn:"驱逐"},{en:"expense",cn:"费用"},{en:"expensive",cn:"昂贵的"},
    {en:"experience",cn:"经验"},{en:"experiment",cn:"实验"},{en:"expert",cn:"专家"},{en:"explicit",cn:"明确的"},
    {en:"explode",cn:"爆炸"},{en:"exploit",cn:"开发"},{en:"explore",cn:"探索"},{en:"export",cn:"出口"},
    {en:"expose",cn:"暴露"},{en:"express",cn:"表达"},{en:"extend",cn:"延伸"},{en:"extension",cn:"扩展"},
    {en:"extensive",cn:"广泛的"},{en:"extent",cn:"程度"},{en:"exterior",cn:"外部的"},{en:"external",cn:"外部的"},
    {en:"extra",cn:"额外的"},{en:"extract",cn:"提取"},{en:"extraordinary",cn:"非凡的"},{en:"extreme",cn:"极端的"},
    {en:"fabricate",cn:"制造"},{en:"facet",cn:"方面"},{en:"facilitate",cn:"促进"},{en:"faction",cn:"派系"},
    {en:"factor",cn:"因素"},{en:"faculty",cn:"教员"},{en:"fade",cn:"褪色"},{en:"fail",cn:"失败"},
    {en:"faint",cn:"微弱的"},{en:"fair",cn:"公平的"},{en:"faith",cn:"信念"},{en:"fake",cn:"假的"},
    {en:"fame",cn:"名声"},{en:"familiar",cn:"熟悉的"},{en:"fancy",cn:"花哨的"},{en:"fantasy",cn:"幻想"},
    {en:"fare",cn:"票价"},{en:"fascinate",cn:"着迷"},{en:"fashion",cn:"时尚"},{en:"fatal",cn:"致命的"},
    {en:"fatigue",cn:"疲劳"},{en:"fault",cn:"过错"},{en:"favor",cn:"赞成"},{en:"fear",cn:"恐惧"},
    {en:"feat",cn:"壮举"},{en:"feature",cn:"特征"},{en:"federal",cn:"联邦的"},{en:"fee",cn:"费用"},
    {en:"feedback",cn:"反馈"},{en:"female",cn:"女性"},{en:"fertile",cn:"肥沃的"},{en:"festival",cn:"节日"},
    {en:"fetch",cn:"取来"},{en:"fever",cn:"发烧"},{en:"fiber",cn:"纤维"},{en:"fierce",cn:"激烈的"},
    {en:"figure",cn:"人物"},{en:"file",cn:"文件"},{en:"finance",cn:"金融"},{en:"financial",cn:"金融的"},
    {en:"finding",cn:"发现"},{en:"fiscal",cn:"财政的"},{en:"fix",cn:"修理"},{en:"fixture",cn:"固定装置"},
    {en:"flank",cn:"侧面"},{en:"flaw",cn:"缺陷"},{en:"flee",cn:"逃跑"},{en:"flexible",cn:"灵活的"},
    {en:"fling",cn:"投掷"},{en:"float",cn:"漂浮"},{en:"flock",cn:"群"},{en:"flourish",cn:"繁荣"},
    {en:"fluctuate",cn:"波动"},{en:"flush",cn:"冲洗"},{en:"focus",cn:"焦点"},{en:"folklore",cn:"民间传说"},
    {en:"forbid",cn:"禁止"},{en:"forecast",cn:"预测"},{en:"foreign",cn:"外国的"},{en:"forge",cn:"锻造"},
    {en:"formal",cn:"正式的"},{en:"format",cn:"格式"},{en:"formation",cn:"形成"},{en:"former",cn:"以前的"},
    {en:"formidable",cn:"强大的"},{en:"formulate",cn:"制定"},{en:"forth",cn:"向前"},{en:"fortune",cn:"财富"},
    {en:"forward",cn:"向前"},{en:"foster",cn:"培养"},{en:"foundation",cn:"基础"},{en:"fraction",cn:"分数"},
    {en:"fragile",cn:"脆弱的"},{en:"fragrance",cn:"香味"},{en:"framework",cn:"框架"},{en:"friction",cn:"摩擦"},
    {en:"fringe",cn:"边缘"},{en:"frontier",cn:"前沿"},{en:"frustrate",cn:"挫败"},{en:"fulfill",cn:"实现"},
    {en:"function",cn:"功能"},{en:"fund",cn:"基金"},{en:"fundamental",cn:"基本的"},{en:"funeral",cn:"葬礼"},
    {en:"furnish",cn:"提供"},{en:"furthermore",cn:"此外"},{en:"fury",cn:"狂怒"},{en:"fuse",cn:"融合"},
    {en:"fusion",cn:"融合"},{en:"fuss",cn:"大惊小怪"},
  ],
// Level 3: 考研词汇
  3: [
    {en:"abide",cn:"遵守"},{en:"abolish",cn:"废除"},{en:"abrupt",cn:"突然的"},{en:"absent",cn:"缺席的"},
    {en:"absorb",cn:"吸收"},{en:"abstract",cn:"抽象的"},{en:"absurd",cn:"荒谬的"},{en:"abundance",cn:"丰富"},
    {en:"abuse",cn:"滥用"},{en:"accelerate",cn:"加速"},{en:"access",cn:"访问"},{en:"accommodate",cn:"容纳"},
    {en:"accomplish",cn:"完成"},{en:"accord",cn:"一致"},{en:"account",cn:"账户"},{en:"accumulate",cn:"积累"},
    {en:"accurate",cn:"精确的"},{en:"accuse",cn:"指控"},{en:"accustom",cn:"使习惯"},{en:"acquaint",cn:"使了解"},
    {en:"acquire",cn:"获得"},{en:"activate",cn:"激活"},{en:"acute",cn:"急性的"},{en:"adapt",cn:"适应"},
    {en:"addict",cn:"使上瘾"},{en:"adequate",cn:"足够的"},{en:"adhere",cn:"坚持"},{en:"adjacent",cn:"邻近的"},
    {en:"adjust",cn:"调整"},{en:"administer",cn:"管理"},{en:"admire",cn:"钦佩"},{en:"admit",cn:"承认"},
    {en:"adolescent",cn:"青少年"},{en:"adopt",cn:"采用"},{en:"adore",cn:"崇拜"},{en:"advance",cn:"前进"},
    {en:"advantage",cn:"优势"},{en:"adverse",cn:"不利的"},{en:"advocate",cn:"提倡"},{en:"aesthetic",cn:"审美的"},
    {en:"affect",cn:"影响"},{en:"affection",cn:"感情"},{en:"affiliate",cn:"附属"},{en:"affirm",cn:"肯定"},
    {en:"afford",cn:"负担得起"},{en:"agenda",cn:"议程"},{en:"aggravate",cn:"加重"},{en:"aggregate",cn:"总计"},
    {en:"agitate",cn:"煽动"},{en:"alert",cn:"警觉的"},{en:"alien",cn:"外星的"},{en:"align",cn:"对齐"},
    {en:"allege",cn:"声称"},{en:"alleviate",cn:"减轻"},{en:"alliance",cn:"联盟"},{en:"allocate",cn:"分配"},
    {en:"allow",cn:"允许"},{en:"allowance",cn:"津贴"},{en:"ally",cn:"盟友"},{en:"alter",cn:"改变"},
    {en:"alternative",cn:"替代的"},{en:"altitude",cn:"高度"},{en:"amateur",cn:"业余的"},{en:"ambiguous",cn:"模棱两可的"},
    {en:"ambition",cn:"野心"},{en:"amend",cn:"修正"},{en:"ample",cn:"充足的"},{en:"amplify",cn:"放大"},
    {en:"analogy",cn:"类比"},{en:"analyse",cn:"分析"},{en:"anchor",cn:"锚"},{en:"announce",cn:"宣布"},
    {en:"annual",cn:"年度的"},{en:"anonymous",cn:"匿名的"},{en:"anticipate",cn:"预期"},{en:"antique",cn:"古董"},
    {en:"anxiety",cn:"焦虑"},{en:"apparatus",cn:"装置"},{en:"apparent",cn:"明显的"},{en:"appeal",cn:"呼吁"},
    {en:"appetite",cn:"食欲"},{en:"applaud",cn:"鼓掌"},{en:"appliance",cn:"电器"},{en:"applicable",cn:"适用的"},
    {en:"applicant",cn:"申请人"},{en:"appraise",cn:"评估"},{en:"appreciate",cn:"感激"},{en:"apprehend",cn:"逮捕"},
    {en:"approach",cn:"接近"},{en:"appropriate",cn:"适当的"},{en:"approve",cn:"批准"},{en:"apt",cn:"恰当的"},
    {en:"arbitrary",cn:"任意的"},{en:"arise",cn:"出现"},{en:"arithmetic",cn:"算术"},{en:"arouse",cn:"唤起"},
    {en:"array",cn:"数组"},{en:"arrest",cn:"逮捕"},{en:"arrogant",cn:"傲慢的"},{en:"articulate",cn:"清晰表达"},
    {en:"artificial",cn:"人工的"},{en:"ascend",cn:"上升"},{en:"ascertain",cn:"确定"},{en:"aspect",cn:"方面"},
    {en:"aspire",cn:"渴望"},{en:"assault",cn:"攻击"},{en:"assemble",cn:"组装"},{en:"assert",cn:"断言"},
    {en:"assess",cn:"评估"},{en:"asset",cn:"资产"},{en:"assign",cn:"分配"},{en:"assist",cn:"协助"},
    {en:"associate",cn:"联系"},{en:"assume",cn:"假设"},{en:"assure",cn:"保证"},{en:"astonish",cn:"使惊讶"},
    {en:"atmosphere",cn:"气氛"},{en:"attach",cn:"附上"},{en:"attain",cn:"达到"},{en:"attempt",cn:"尝试"},
    {en:"attend",cn:"参加"},{en:"attitude",cn:"态度"},{en:"attorney",cn:"律师"},{en:"attract",cn:"吸引"},
    {en:"attribute",cn:"属性"},{en:"authentic",cn:"真实的"},{en:"authority",cn:"权威"},{en:"authorize",cn:"授权"},
    {en:"automatic",cn:"自动的"},{en:"autonomy",cn:"自治"},{en:"available",cn:"可用的"},{en:"avert",cn:"避免"},
    {en:"avoid",cn:"避免"},{en:"award",cn:"奖"},{en:"aware",cn:"意识到的"},{en:"awful",cn:"糟糕的"},
    {en:"awkward",cn:"尴尬的"},{en:"bachelor",cn:"学士"},{en:"baffle",cn:"使困惑"},{en:"balance",cn:"平衡"},
    {en:"ban",cn:"禁止"},{en:"band",cn:"乐队"},{en:"bankrupt",cn:"破产的"},{en:"bare",cn:"裸露的"},
    {en:"barely",cn:"几乎不"},{en:"bargain",cn:"便宜货"},{en:"barrier",cn:"障碍"},{en:"batch",cn:"批次"},
    {en:"beam",cn:"光束"},{en:"behalf",cn:"代表"},{en:"behave",cn:"行为"},{en:"benefit",cn:"利益"},
    {en:"benign",cn:"良性的"},{en:"betray",cn:"背叛"},{en:"bias",cn:"偏见"},{en:"bid",cn:"出价"},
    {en:"bind",cn:"绑"},{en:"bizarre",cn:"奇异的"},{en:"blade",cn:"刀片"},{en:"blast",cn:"爆炸"},
    {en:"blaze",cn:"火焰"},{en:"bleed",cn:"流血"},{en:"blend",cn:"混合"},{en:"bless",cn:"祝福"},
    {en:"block",cn:"阻塞"},{en:"bloom",cn:"开花"},{en:"blunder",cn:"大错"},{en:"board",cn:"板"},
    {en:"boast",cn:"吹嘘"},{en:"bold",cn:"大胆的"},{en:"bolt",cn:"螺栓"},{en:"bond",cn:"纽带"},
    {en:"boost",cn:"促进"},{en:"border",cn:"边界"},{en:"bother",cn:"打扰"},{en:"bounce",cn:"弹跳"},
    {en:"bound",cn:"一定的"},{en:"boundary",cn:"边界"},{en:"branch",cn:"分支"},{en:"brand",cn:"品牌"},
    {en:"breakdown",cn:"故障"},{en:"breakthrough",cn:"突破"},{en:"breed",cn:"品种"},{en:"breeze",cn:"微风"},
    {en:"brief",cn:"简短的"},{en:"brilliant",cn:"辉煌的"},{en:"brisk",cn:"轻快的"},{en:"broadcast",cn:"广播"},
    {en:"browse",cn:"浏览"},{en:"bruise",cn:"瘀伤"},{en:"budget",cn:"预算"},{en:"bulk",cn:"大量"},
    {en:"bullet",cn:"子弹"},{en:"bump",cn:"碰撞"},{en:"bunch",cn:"束"},{en:"burden",cn:"负担"},
    {en:"bureau",cn:"局"},{en:"bureaucracy",cn:"官僚主义"},{en:"burst",cn:"爆发"},{en:"calculate",cn:"计算"},
    {en:"campaign",cn:"运动"},{en:"cancel",cn:"取消"},{en:"candidate",cn:"候选人"},{en:"capable",cn:"有能力的"},
    {en:"capacity",cn:"容量"},{en:"capture",cn:"捕获"},{en:"carbon",cn:"碳"},{en:"career",cn:"职业"},
    {en:"cargo",cn:"货物"},{en:"cascade",cn:"级联"},{en:"casual",cn:"随意的"},{en:"casualty",cn:"伤亡"},
    {en:"catalog",cn:"目录"},{en:"catastrophe",cn:"灾难"},{en:"category",cn:"类别"},{en:"cater",cn:"迎合"},
    {en:"cease",cn:"停止"},{en:"censor",cn:"审查"},{en:"certificate",cn:"证书"},{en:"challenge",cn:"挑战"},
    {en:"champion",cn:"冠军"},{en:"channel",cn:"频道"},{en:"chapter",cn:"章节"},{en:"character",cn:"角色"},
    {en:"charge",cn:"收费"},{en:"charity",cn:"慈善"},{en:"charm",cn:"魅力"},{en:"charter",cn:"宪章"},
    {en:"chase",cn:"追逐"},{en:"cherish",cn:"珍惜"},{en:"chronic",cn:"慢性的"},{en:"circulate",cn:"循环"},
    {en:"circumstance",cn:"情况"},{en:"cite",cn:"引用"},{en:"civil",cn:"民事的"},{en:"civilian",cn:"平民"},
    {en:"claim",cn:"声称"},{en:"clarify",cn:"澄清"},{en:"clash",cn:"冲突"},{en:"classify",cn:"分类"},
    {en:"clause",cn:"条款"},{en:"client",cn:"客户"},{en:"cling",cn:"紧贴"},{en:"clinical",cn:"临床的"},
    {en:"clone",cn:"克隆"},{en:"clue",cn:"线索"},{en:"cluster",cn:"集群"},{en:"coalition",cn:"联盟"},
    {en:"cognitive",cn:"认知的"},{en:"coherent",cn:"连贯的"},{en:"coincide",cn:"巧合"},{en:"collaborate",cn:"合作"},
    {en:"collapse",cn:"倒塌"},{en:"colleague",cn:"同事"},{en:"collision",cn:"碰撞"},{en:"combat",cn:"战斗"},
    {en:"combine",cn:"结合"},{en:"command",cn:"命令"},{en:"commemorate",cn:"纪念"},{en:"commence",cn:"开始"},
    {en:"commend",cn:"表扬"},{en:"comment",cn:"评论"},{en:"commercial",cn:"商业的"},{en:"commission",cn:"委员会"},
    {en:"commit",cn:"犯；承诺"},{en:"committee",cn:"委员会"},{en:"commodity",cn:"商品"},{en:"commonplace",cn:"司空见惯的"},
    {en:"commonwealth",cn:"联邦"},{en:"communicate",cn:"沟通"},{en:"community",cn:"社区"},{en:"compact",cn:"紧凑的"},
    {en:"companion",cn:"同伴"},{en:"comparable",cn:"可比较的"},{en:"comparative",cn:"比较的"},{en:"compare",cn:"比较"},
    {en:"comparison",cn:"比较"},{en:"compel",cn:"强迫"},{en:"compensate",cn:"补偿"},{en:"compete",cn:"竞争"},
    {en:"competent",cn:"有能力的"},{en:"competition",cn:"竞争"},{en:"compile",cn:"编译"},{en:"complain",cn:"抱怨"},
    {en:"complement",cn:"补充"},{en:"complete",cn:"完成"},{en:"complex",cn:"复杂的"},{en:"complicated",cn:"复杂的"},
    {en:"comply",cn:"遵守"},{en:"component",cn:"组件"},{en:"compose",cn:"组成"},{en:"compound",cn:"化合物"},
    {en:"comprehend",cn:"理解"},{en:"comprehensive",cn:"全面的"},{en:"compress",cn:"压缩"},{en:"comprise",cn:"包含"},
    {en:"compromise",cn:"妥协"},{en:"compulsory",cn:"强制的"},{en:"compute",cn:"计算"},{en:"conceal",cn:"隐藏"},
    {en:"concede",cn:"承认"},{en:"conceive",cn:"构想"},{en:"concentrate",cn:"集中"},{en:"concept",cn:"概念"},
    {en:"concern",cn:"关心"},{en:"conclude",cn:"总结"},{en:"concrete",cn:"具体的"},{en:"condemn",cn:"谴责"},
    {en:"conduct",cn:"进行"},{en:"conference",cn:"会议"},{en:"confess",cn:"承认"},{en:"confidence",cn:"信心"},
    {en:"confine",cn:"限制"},{en:"confirm",cn:"确认"},{en:"conflict",cn:"冲突"},{en:"conform",cn:"遵守"},
    {en:"confront",cn:"面对"},{en:"confuse",cn:"困惑"},{en:"congregate",cn:"聚集"},{en:"congress",cn:"国会"},
    {en:"conjunction",cn:"连接"},{en:"connect",cn:"连接"},{en:"conquest",cn:"征服"},{en:"conscience",cn:"良心"},
    {en:"conscious",cn:"有意识的"},{en:"consensus",cn:"共识"},{en:"consent",cn:"同意"},{en:"consequence",cn:"后果"},
    {en:"consequent",cn:"随之发生的"},{en:"conserve",cn:"保存"},{en:"conservative",cn:"保守的"},{en:"consider",cn:"考虑"},
    {en:"considerable",cn:"相当大的"},{en:"consist",cn:"由...组成"},{en:"consistent",cn:"一致的"},{en:"consolidate",cn:"巩固"},
    {en:"conspiracy",cn:"阴谋"},{en:"constant",cn:"恒定的"},{en:"constitute",cn:"构成"},{en:"constitution",cn:"宪法"},
    {en:"constrain",cn:"约束"},{en:"construct",cn:"建造"},{en:"consult",cn:"咨询"},{en:"consume",cn:"消耗"},
    {en:"contact",cn:"接触"},{en:"contain",cn:"包含"},{en:"contaminate",cn:"污染"},{en:"contemplate",cn:"沉思"},
    {en:"contemporary",cn:"当代的"},{en:"contempt",cn:"蔑视"},{en:"contend",cn:"竞争"},{en:"content",cn:"内容"},
    {en:"contest",cn:"竞赛"},{en:"context",cn:"上下文"},{en:"continent",cn:"大陆"},{en:"contingent",cn:"视情况而定的"},
    {en:"contract",cn:"合同"},{en:"contradict",cn:"矛盾"},{en:"contrary",cn:"相反的"},{en:"contrast",cn:"对比"},
    {en:"contribute",cn:"贡献"},{en:"control",cn:"控制"},{en:"controversial",cn:"有争议的"},{en:"controversy",cn:"争论"},
    {en:"convene",cn:"召集"},{en:"convention",cn:"大会"},{en:"converge",cn:"汇聚"},{en:"converse",cn:"交谈"},
    {en:"convert",cn:"转换"},{en:"convey",cn:"传达"},{en:"convict",cn:"定罪"},{en:"convince",cn:"说服"},
    {en:"cooperate",cn:"合作"},{en:"cooperative",cn:"合作的"},{en:"coordinate",cn:"协调"},{en:"cope",cn:"应对"},
    {en:"core",cn:"核心"},{en:"corporate",cn:"公司的"},{en:"correlate",cn:"相关"},{en:"correspond",cn:"对应"},
    {en:"correspondent",cn:"记者"},{en:"corrode",cn:"腐蚀"},{en:"corrupt",cn:"腐败的"},{en:"counsel",cn:"建议"},
    {en:"count",cn:"计数"},{en:"counterpart",cn:"对应物"},{en:"coup",cn:"政变"},{en:"courage",cn:"勇气"},
    {en:"course",cn:"课程"},{en:"court",cn:"法庭"},{en:"courtesy",cn:"礼貌"},{en:"coverage",cn:"覆盖范围"},
    {en:"crack",cn:"裂缝"},{en:"craft",cn:"工艺"},{en:"crash",cn:"碰撞"},{en:"create",cn:"创造"},
    {en:"credential",cn:"资格"},{en:"credit",cn:"信用"},{en:"crew",cn:"船员"},{en:"crime",cn:"犯罪"},
    {en:"criminal",cn:"犯罪的"},{en:"cripple",cn:"使残废"},{en:"crisis",cn:"危机"},{en:"criterion",cn:"标准"},
    {en:"critical",cn:"关键的"},{en:"critique",cn:"批评"},{en:"crucial",cn:"至关重要的"},{en:"crude",cn:"粗糙的"},
    {en:"crush",cn:"压碎"},{en:"cultivate",cn:"培养"},{en:"culture",cn:"文化"},{en:"cumulative",cn:"累积的"},
    {en:"curb",cn:"抑制"},{en:"curiosity",cn:"好奇心"},{en:"currency",cn:"货币"},{en:"current",cn:"当前的"},
    {en:"curriculum",cn:"课程"},{en:"curtail",cn:"削减"},{en:"curve",cn:"曲线"},{en:"customary",cn:"习惯的"},
    {en:"cynical",cn:"愤世嫉俗的"},{en:"damage",cn:"损害"},{en:"daring",cn:"大胆的"},{en:"data",cn:"数据"},
    {en:"daunting",cn:"令人畏惧的"},{en:"dazzle",cn:"使目眩"},{en:"deadline",cn:"截止日期"},{en:"debate",cn:"辩论"},
    {en:"debut",cn:"首次亮相"},{en:"decade",cn:"十年"},{en:"deceive",cn:"欺骗"},{en:"decent",cn:"体面的"},
    {en:"decisive",cn:"决定性的"},{en:"declare",cn:"宣布"},{en:"decline",cn:"下降"},{en:"decorate",cn:"装饰"},
    {en:"decrease",cn:"减少"},{en:"dedicate",cn:"奉献"},{en:"deem",cn:"认为"},{en:"default",cn:"默认"},
    {en:"defeat",cn:"击败"},{en:"defect",cn:"缺陷"},{en:"defend",cn:"防御"},{en:"deficit",cn:"赤字"},
    {en:"define",cn:"定义"},{en:"definite",cn:"明确的"},{en:"defy",cn:"违抗"},{en:"delegate",cn:"委托"},
    {en:"deliberate",cn:"故意的"},{en:"delicate",cn:"精致的"},{en:"deliver",cn:"交付"},{en:"demand",cn:"需求"},
    {en:"democracy",cn:"民主"},{en:"demonstrate",cn:"演示"},{en:"denote",cn:"表示"},{en:"denounce",cn:"谴责"},
    {en:"dense",cn:"密集的"},{en:"deny",cn:"否认"},{en:"depart",cn:"离开"},{en:"department",cn:"部门"},
    {en:"depend",cn:"依赖"},{en:"depict",cn:"描绘"},{en:"deploy",cn:"部署"},{en:"deposit",cn:"存款"},
    {en:"deprive",cn:"剥夺"},{en:"derive",cn:"源自"},{en:"descend",cn:"下降"},{en:"describe",cn:"描述"},
    {en:"deserve",cn:"值得"},{en:"design",cn:"设计"},{en:"designate",cn:"指定"},{en:"desire",cn:"渴望"},
    {en:"despair",cn:"绝望"},{en:"desperate",cn:"绝望的"},{en:"despite",cn:"尽管"},{en:"destination",cn:"目的地"},
    {en:"destiny",cn:"命运"},{en:"destroy",cn:"摧毁"},{en:"detach",cn:"分离"},{en:"detail",cn:"细节"},
    {en:"detain",cn:"拘留"},{en:"detect",cn:"检测"},{en:"deteriorate",cn:"恶化"},{en:"determine",cn:"确定"},
    {en:"develop",cn:"发展"},{en:"deviate",cn:"偏离"},{en:"device",cn:"设备"},{en:"devise",cn:"设计"},
    {en:"devote",cn:"奉献"},{en:"diagnose",cn:"诊断"},{en:"differ",cn:"不同"},{en:"differentiate",cn:"区分"},
    {en:"diffuse",cn:"扩散"},{en:"digest",cn:"消化"},{en:"dignity",cn:"尊严"},{en:"dilemma",cn:"困境"},
    {en:"dimension",cn:"维度"},{en:"diminish",cn:"减少"},{en:"diplomat",cn:"外交官"},{en:"disable",cn:"使残疾"},
    {en:"disappoint",cn:"使失望"},{en:"disaster",cn:"灾难"},{en:"discipline",cn:"纪律"},{en:"disclose",cn:"披露"},
    {en:"discount",cn:"折扣"},{en:"discourse",cn:"话语"},{en:"discover",cn:"发现"},{en:"discrepancy",cn:"差异"},
    {en:"discrete",cn:"离散的"},{en:"discriminate",cn:"歧视"},{en:"disguise",cn:"伪装"},{en:"dismiss",cn:"解雇"},
    {en:"disorder",cn:"混乱"},{en:"disperse",cn:"分散"},{en:"displace",cn:"取代"},{en:"display",cn:"展示"},
    {en:"dispose",cn:"处置"},{en:"disregard",cn:"无视"},{en:"disrupt",cn:"破坏"},{en:"dissolve",cn:"溶解"},
    {en:"distinguish",cn:"区分"},{en:"distort",cn:"扭曲"},{en:"distract",cn:"分散注意力"},{en:"distress",cn:"苦恼"},
    {en:"distribute",cn:"分配"},{en:"disturb",cn:"打扰"},{en:"diverse",cn:"多样的"},{en:"divert",cn:"转移"},
    {en:"divine",cn:"神圣的"},{en:"document",cn:"文件"},{en:"doctrine",cn:"学说"},{en:"domain",cn:"领域"},
    {en:"domestic",cn:"国内的"},{en:"dominant",cn:"主导的"},{en:"donate",cn:"捐赠"},{en:"donor",cn:"捐赠者"},
    {en:"doom",cn:"厄运"},{en:"dose",cn:"剂量"},{en:"draft",cn:"草案"},{en:"drain",cn:"排水"},
    {en:"dramatic",cn:"戏剧性的"},{en:"drastic",cn:"激烈的"},{en:"dread",cn:"恐惧"},{en:"drift",cn:"漂流"},
    {en:"drought",cn:"干旱"},{en:"dub",cn:"配音"},{en:"dubious",cn:"可疑的"},{en:"dump",cn:"倾倒"},
    {en:"duplicate",cn:"复制"},{en:"durable",cn:"耐用的"},{en:"duration",cn:"持续时间"},{en:"dwell",cn:"居住"},
    {en:"dynamic",cn:"动态的"},{en:"earnest",cn:"认真的"},{en:"ease",cn:"轻松"},{en:"eccentric",cn:"古怪的"},
    {en:"eclipse",cn:"日食"},{en:"ecology",cn:"生态学"},{en:"economic",cn:"经济的"},{en:"economy",cn:"经济"},
    {en:"edit",cn:"编辑"},{en:"edition",cn:"版本"},{en:"editor",cn:"编辑"},{en:"educate",cn:"教育"},
    {en:"effect",cn:"效果"},{en:"effective",cn:"有效的"},{en:"efficient",cn:"高效的"},{en:"elaborate",cn:"精心制作"},
    {en:"elect",cn:"选举"},{en:"election",cn:"选举"},{en:"electric",cn:"电的"},{en:"electronic",cn:"电子的"},
    {en:"elegant",cn:"优雅的"},{en:"element",cn:"元素"},{en:"elevate",cn:"提升"},{en:"eligible",cn:"有资格的"},
    {en:"eliminate",cn:"消除"},{en:"elite",cn:"精英"},{en:"eloquent",cn:"雄辩的"},{en:"emancipate",cn:"解放"},
    {en:"embark",cn:"着手"},{en:"embarrass",cn:"使尴尬"},{en:"embody",cn:"体现"},{en:"embrace",cn:"拥抱"},
    {en:"emerge",cn:"出现"},{en:"emergency",cn:"紧急情况"},{en:"emit",cn:"发出"},{en:"emotion",cn:"情感"},
    {en:"emphasis",cn:"强调"},{en:"emphasize",cn:"强调"},{en:"empirical",cn:"经验的"},{en:"employ",cn:"雇用"},
    {en:"employee",cn:"雇员"},{en:"employment",cn:"就业"},{en:"enable",cn:"使能够"},{en:"encounter",cn:"遇到"},
    {en:"encourage",cn:"鼓励"},{en:"endanger",cn:"危及"},{en:"endeavor",cn:"努力"},{en:"endorse",cn:"赞同"},
    {en:"endure",cn:"忍受"},{en:"enforce",cn:"执行"},{en:"engage",cn:"参与"},{en:"enhance",cn:"增强"},
    {en:"enlighten",cn:"启发"},{en:"enormous",cn:"巨大的"},{en:"enrich",cn:"丰富"},{en:"enroll",cn:"注册"},
    {en:"ensure",cn:"确保"},{en:"ensue",cn:"接着发生"},{en:"entail",cn:"需要"},{en:"enterprise",cn:"企业"},
    {en:"enthusiastic",cn:"热情的"},{en:"entire",cn:"整个"},{en:"entity",cn:"实体"},{en:"entrepreneur",cn:"企业家"},
    {en:"envisage",cn:"设想"},{en:"environment",cn:"环境"},{en:"epidemic",cn:"流行病"},{en:"equal",cn:"平等的"},
    {en:"equip",cn:"装备"},{en:"equipment",cn:"设备"},{en:"equivalent",cn:"等价的"},{en:"era",cn:"时代"},
    {en:"erode",cn:"侵蚀"},{en:"erupt",cn:"爆发"},{en:"escape",cn:"逃跑"},{en:"escort",cn:"护送"},
    {en:"essence",cn:"本质"},{en:"essential",cn:"必要的"},{en:"establish",cn:"建立"},{en:"estate",cn:"房产"},
    {en:"esteem",cn:"尊重"},{en:"estimate",cn:"估计"},{en:"evacuate",cn:"疏散"},{en:"evaluate",cn:"评估"},
    {en:"evoke",cn:"唤起"},{en:"evolution",cn:"进化"},{en:"evolve",cn:"进化"},{en:"exaggerate",cn:"夸大"},
    {en:"exceed",cn:"超过"},{en:"excel",cn:"擅长"},{en:"exception",cn:"例外"},{en:"excerpt",cn:"摘录"},
    {en:"excess",cn:"过量"},{en:"exchange",cn:"交换"},{en:"exclude",cn:"排除"},{en:"exclusive",cn:"排他的"},
    {en:"execute",cn:"执行"},{en:"exempt",cn:"豁免"},{en:"exert",cn:"施加"},{en:"exhaust",cn:"耗尽"},
    {en:"exhibit",cn:"展览"},{en:"exile",cn:"流放"},{en:"exist",cn:"存在"},{en:"expand",cn:"扩展"},
    {en:"expect",cn:"期望"},{en:"expedition",cn:"远征"},{en:"expel",cn:"驱逐"},{en:"expense",cn:"费用"},
    {en:"experience",cn:"经验"},{en:"experiment",cn:"实验"},{en:"expert",cn:"专家"},{en:"explicit",cn:"明确的"},
    {en:"explode",cn:"爆炸"},{en:"exploit",cn:"开发"},{en:"explore",cn:"探索"},{en:"export",cn:"出口"},
    {en:"expose",cn:"暴露"},{en:"express",cn:"表达"},{en:"extend",cn:"延伸"},{en:"extension",cn:"扩展"},
    {en:"extensive",cn:"广泛的"},{en:"extent",cn:"程度"},{en:"exterior",cn:"外部的"},{en:"external",cn:"外部的"},
    {en:"extract",cn:"提取"},{en:"extraordinary",cn:"非凡的"},{en:"extreme",cn:"极端的"},{en:"fabricate",cn:"制造"},
    {en:"facet",cn:"方面"},{en:"facilitate",cn:"促进"},{en:"faction",cn:"派系"},{en:"factor",cn:"因素"},
    {en:"faculty",cn:"教员"},{en:"fade",cn:"褪色"},{en:"faint",cn:"微弱的"},{en:"fair",cn:"公平的"},
    {en:"faith",cn:"信念"},{en:"fake",cn:"假的"},{en:"fame",cn:"名声"},{en:"familiar",cn:"熟悉的"},
    {en:"fancy",cn:"花哨的"},{en:"fantasy",cn:"幻想"},{en:"fare",cn:"票价"},{en:"fascinate",cn:"着迷"},
    {en:"fashion",cn:"时尚"},{en:"fatal",cn:"致命的"},{en:"fatigue",cn:"疲劳"},{en:"fault",cn:"过错"},
    {en:"favor",cn:"赞成"},{en:"fear",cn:"恐惧"},{en:"feat",cn:"壮举"},{en:"feature",cn:"特征"},
    {en:"federal",cn:"联邦的"},{en:"fee",cn:"费用"},{en:"feedback",cn:"反馈"},{en:"female",cn:"女性"},
    {en:"fertile",cn:"肥沃的"},{en:"fetch",cn:"取来"},{en:"fever",cn:"发烧"},{en:"fiber",cn:"纤维"},
    {en:"fierce",cn:"激烈的"},{en:"figure",cn:"人物"},{en:"file",cn:"文件"},{en:"finance",cn:"金融"},
    {en:"financial",cn:"金融的"},{en:"finding",cn:"发现"},{en:"fiscal",cn:"财政的"},{en:"fixture",cn:"固定装置"},
    {en:"flank",cn:"侧面"},{en:"flaw",cn:"缺陷"},{en:"flee",cn:"逃跑"},{en:"flexible",cn:"灵活的"},
    {en:"fling",cn:"投掷"},{en:"float",cn:"漂浮"},{en:"flock",cn:"群"},{en:"flourish",cn:"繁荣"},
    {en:"fluctuate",cn:"波动"},{en:"flush",cn:"冲洗"},{en:"focus",cn:"焦点"},{en:"folklore",cn:"民间传说"},
    {en:"forecast",cn:"预测"},{en:"foreign",cn:"外国的"},{en:"forge",cn:"锻造"},{en:"formal",cn:"正式的"},
    {en:"format",cn:"格式"},{en:"formation",cn:"形成"},{en:"former",cn:"以前的"},{en:"formidable",cn:"强大的"},
    {en:"formulate",cn:"制定"},{en:"forth",cn:"向前"},{en:"fortune",cn:"财富"},{en:"forward",cn:"向前"},
    {en:"foster",cn:"培养"},{en:"foundation",cn:"基础"},{en:"fraction",cn:"分数"},{en:"fragile",cn:"脆弱的"},
    {en:"fragrance",cn:"香味"},{en:"framework",cn:"框架"},{en:"friction",cn:"摩擦"},{en:"fringe",cn:"边缘"},
    {en:"frontier",cn:"前沿"},{en:"frustrate",cn:"挫败"},{en:"fulfill",cn:"实现"},{en:"function",cn:"功能"},
    {en:"fund",cn:"基金"},{en:"fundamental",cn:"基本的"},{en:"funeral",cn:"葬礼"},{en:"furnish",cn:"提供"},
    {en:"furthermore",cn:"此外"},{en:"fury",cn:"狂怒"},{en:"fuse",cn:"融合"},{en:"fusion",cn:"融合"},
    {en:"fuss",cn:"大惊小怪"},{en:"gain",cn:"获得"},{en:"gallery",cn:"画廊"},{en:"gap",cn:"差距"},
    {en:"gather",cn:"聚集"},{en:"gear",cn:"齿轮"},{en:"gender",cn:"性别"},{en:"gene",cn:"基因"},
    {en:"generate",cn:"产生"},{en:"generation",cn:"一代"},{en:"generous",cn:"慷慨的"},{en:"genius",cn:"天才"},
    {en:"genuine",cn:"真正的"},{en:"gesture",cn:"手势"},{en:"global",cn:"全球的"},{en:"glory",cn:"荣耀"},
    {en:"govern",cn:"统治"},{en:"government",cn:"政府"},{en:"grab",cn:"抓取"},{en:"grace",cn:"优雅"},
    {en:"gradual",cn:"逐渐的"},{en:"grant",cn:"授予"},{en:"graphic",cn:"图形的"},{en:"grasp",cn:"掌握"},
    {en:"grateful",cn:"感激的"},{en:"grave",cn:"严重的"},{en:"grief",cn:"悲伤"},{en:"grind",cn:"磨"},
    {en:"grip",cn:"紧握"},{en:"gross",cn:"总的"},{en:"guarantee",cn:"保证"},{en:"guard",cn:"守卫"},
    {en:"guide",cn:"指导"},{en:"guilty",cn:"有罪的"},{en:"halt",cn:"停止"},{en:"handful",cn:"少数"},
    {en:"handle",cn:"处理"},{en:"harbor",cn:"港口"},{en:"harden",cn:"变硬"},{en:"hardware",cn:"硬件"},
    {en:"harmony",cn:"和谐"},{en:"harsh",cn:" harsh"},{en:"harvest",cn:"收获"},{en:"haste",cn:"匆忙"},
    {en:"hatred",cn:"仇恨"},{en:"haul",cn:"拖运"},{en:"haunt",cn:"萦绕"},{en:"heal",cn:"治愈"},
    {en:"heap",cn:"堆"},{en:"hedge",cn:"对冲"},{en:"highlight",cn:"强调"},{en:"hint",cn:"暗示"},
    {en:"hire",cn:"雇用"},{en:"hold",cn:"持有"},{en:"honor",cn:"荣誉"},{en:"hook",cn:"钩"},
    {en:"horizon",cn:"地平线"},{en:"horizontal",cn:"水平的"},{en:"hostile",cn:"敌对的"},{en:"household",cn:"家庭"},
    {en:"humble",cn:" humble"},{en:"hunger",cn:"饥饿"},{en:"hunt",cn:"打猎"},{en:"hurry",cn:"匆忙"},
    {en:"ideal",cn:"理想的"},{en:"identical",cn:"相同的"},{en:"identify",cn:"识别"},{en:"identity",cn:"身份"},
    {en:"ignorance",cn:"无知"},{en:"ignore",cn:"忽略"},{en:"illegal",cn:"非法的"},{en:"illustrate",cn:"说明"},
    {en:"image",cn:"图像"},{en:"imagination",cn:"想象力"},{en:"imagine",cn:"想象"},{en:"imitate",cn:"模仿"},
    {en:"immediate",cn:"立即的"},{en:"immense",cn:"巨大的"},{en:"immune",cn:"免疫的"},{en:"impact",cn:"影响"},
    {en:"implement",cn:"实施"},{en:"implication",cn:"含义"},{en:"implicit",cn:"含蓄的"},{en:"imply",cn:"暗示"},
    {en:"import",cn:"进口"},{en:"impose",cn:"强加"},{en:"impress",cn:"给...留下印象"},{en:"impression",cn:"印象"},
    {en:"impressive",cn:"令人印象深刻的"},{en:"improve",cn:"改善"},{en:"improvement",cn:"改善"},{en:"incident",cn:"事件"},
    {en:"incline",cn:"倾斜"},{en:"include",cn:"包括"},{en:"income",cn:"收入"},{en:"incorporate",cn:"合并"},
    {en:"increase",cn:"增加"},{en:"incredible",cn:"难以置信的"},{en:"incur",cn:"招致"},{en:"indicate",cn:"指出"},
    {en:"individual",cn:"个人"},{en:"induce",cn:"诱导"},{en:"industrial",cn:"工业的"},{en:"industry",cn:"行业"},
    {en:"inevitable",cn:"不可避免的"},{en:"infant",cn:"婴儿"},{en:"infect",cn:"感染"},{en:"infer",cn:"推断"},
    {en:"inferior",cn:" inferior"},{en:"inflation",cn:"通货膨胀"},{en:"influence",cn:"影响"},{en:"inform",cn:"通知"},
    {en:"ingredient",cn:"成分"},{en:"inhabit",cn:"居住"},{en:"inherent",cn:"固有的"},{en:"inherit",cn:"继承"},
    {en:"initial",cn:"初始的"},{en:"initiate",cn:"发起"},{en:"initiative",cn:"倡议"},{en:"inject",cn:"注射"},
    {en:"innocent",cn:"无辜的"},{en:"innovation",cn:"创新"},{en:"input",cn:"输入"},{en:"inquire",cn:"询问"},
    {en:"insert",cn:"插入"},{en:"insight",cn:"洞察力"},{en:"insist",cn:"坚持"},{en:"inspect",cn:"检查"},
    {en:"inspire",cn:"启发"},{en:"install",cn:"安装"},{en:"instance",cn:"实例"},{en:"instant",cn:"立即的"},
    {en:"instinct",cn:"本能"},{en:"institute",cn:" institute"},{en:"institution",cn:"机构"},{en:"instruct",cn:"指导"},
    {en:"instrument",cn:" instrument"},{en:"insult",cn:"侮辱"},{en:"insurance",cn:"保险"},{en:"integrate",cn:"整合"},
    {en:"intellectual",cn:"知识分子"},{en:"intelligence",cn:" intelligence"},{en:"intelligent",cn:" intelligent"},
    {en:"intend",cn:"打算"},{en:"intense",cn:" intense"},{en:"intention",cn:"意图"},{en:"interact",cn:"互动"},
    {en:"interest",cn:"兴趣"},{en:"interfere",cn:"干涉"},{en:"interior",cn:"内部的"},{en:"internal",cn:"内部的"},
    {en:"interpret",cn:"解释"},{en:"interval",cn:"间隔"},{en:"intervene",cn:"干预"},{en:"intimate",cn:"亲密的"},
    {en:"invade",cn:"入侵"},{en:"invest",cn:"投资"},{en:"investigate",cn:"调查"},{en:"investment",cn:"投资"},
    {en:"invisible",cn:"看不见的"},{en:"involve",cn:"涉及"},{en:"isolate",cn:"隔离"},{en:"issue",cn:"问题"},
    {en:"item",cn:"项目"},{en:"joint",cn:"关节"},{en:"journal",cn:"期刊"},{en:"journalist",cn:"记者"},
    {en:"journey",cn:"旅程"},{en:"judge",cn:"判断"},{en:"judgment",cn:"判断"},{en:"junior",cn:"初级的"},
    {en:"jury",cn:"陪审团"},{en:"justice",cn:"正义"},{en:"justify",cn:"证明...正当"},{en:"keen",cn:"敏锐的"},
    {en:"label",cn:"标签"},{en:"labor",cn:"劳动"},{en:"landscape",cn:"景观"},{en:"launch",cn:"发射"},
    {en:"layer",cn:"层"},{en:"leadership",cn:"领导力"},{en:"lean",cn:"倾斜"},{en:"leap",cn:"跳跃"},
    {en:"lecture",cn:"讲座"},{en:"legal",cn:"法律的"},{en:"legislation",cn:"立法"},{en:"legitimate",cn:"合法的"},
    {en:"leisure",cn:" leisure"},{en:"lend",cn:"借出"},{en:"liability",cn:"责任"},{en:"liberal",cn:"自由的"},
    {en:"liberate",cn:"解放"},{en:"liberty",cn:"自由"},{en:"license",cn:"许可证"},{en:"likely",cn:"可能的"},
    {en:"likewise",cn:"同样地"},{en:"limit",cn:"限制"},{en:"limitation",cn:"限制"},{en:"line",cn:"线"},
    {en:"link",cn:"链接"},{en:"liquid",cn:"液体"},{en:"literary",cn:"文学的"},{en:"literature",cn:"文学"},
    {en:"load",cn:"负载"},{en:"loan",cn:"贷款"},{en:"local",cn:"本地的"},{en:"locate",cn:"定位"},
    {en:"location",cn:"位置"},{en:"logic",cn:"逻辑"},{en:"logical",cn:"逻辑的"},{en:"long-term",cn:"长期的"},
    {en:"loose",cn:"松的"},{en:"loyal",cn:"忠诚的"},{en:"luggage",cn:"行李"},{en:"luxury",cn:"奢侈"},
    {en:"magic",cn:"魔术"},{en:"magnificent",cn:"壮丽的"},{en:"magnitude",cn:" magnitude"},{en:"maintain",cn:"维持"},
    {en:"major",cn:"主要的"},{en:"majority",cn:"多数"},{en:"manage",cn:"管理"},{en:"management",cn:"管理"},
    {en:"manifest",cn:"显现"},{en:"manipulate",cn:"操纵"},{en:"manner",cn:"方式"},{en:"manual",cn:"手动的"},
    {en:"manufacture",cn:"制造"},{en:"margin",cn:" margin"},{en:"mass",cn:"质量"},{en:"massive",cn:" massive"},
    {en:"master",cn:"掌握"},{en:"match",cn:"匹配"},{en:"matter",cn:"物质"},{en:"mature",cn:"成熟的"},
    {en:"maximum",cn:"最大的"},{en:"means",cn:" means"},{en:"measure",cn:"测量"},{en:"mechanism",cn:"机制"},
    {en:"media",cn:"媒体"},{en:"medium",cn:" medium"},{en:"melt",cn:"融化"},{en:"membership",cn:"会员资格"},
    {en:"mental",cn:"心理的"},{en:"mention",cn:"提到"},{en:"merchant",cn:"商人"},{en:"mercy",cn:" mercy"},
    {en:"mere",cn:"仅仅"},{en:"merge",cn:"合并"},{en:"merit",cn:"优点"},{en:"method",cn:"方法"},
    {en:"military",cn:"军事的"},{en:"mine",cn:" mine"},{en:"mineral",cn:"矿物"},{en:"minimum",cn:"最小的"},
    {en:"minister",cn:"部长"},{en:"ministry",cn:"部"},{en:"minor",cn:" minor"},{en:"minority",cn:"少数"},
    {en:"miracle",cn:"奇迹"},{en:"mirror",cn:"镜子"},{en:"mislead",cn:"误导"},{en:"mission",cn:"使命"},
    {en:"mobile",cn:"移动的"},{en:"mode",cn:"模式"},{en:"moderate",cn:" moderate"},{en:"modern",cn:"现代的"},
    {en:"modify",cn:"修改"},{en:"module",cn:"模块"},{en:"moist",cn:"潮湿的"},{en:"molecule",cn:"分子"},
    {en:"monitor",cn:"监控"},{en:"moral",cn:"道德的"},{en:"moreover",cn:"此外"},{en:"mortgage",cn:"抵押贷款"},
    {en:"motion",cn:"运动"},{en:"motivate",cn:"激励"},{en:"motive",cn:"动机"},{en:"mount",cn:"安装"},
    {en:"multiple",cn:"多个的"},{en:"multiply",cn:"乘"},{en:"murder",cn:"谋杀"},{en:"muscle",cn:"肌肉"},
    {en:"mutual",cn:"相互的"},{en:"mystery",cn:"谜"},{en:"myth",cn:"神话"},{en:"naked",cn:"裸体的"},
    {en:"narrative",cn:"叙事"},{en:"narrow",cn:"窄的"},{en:"nasty",cn:" nasty"},{en:"nation",cn:"国家"},
    {en:"national",cn:"国家的"},{en:"native",cn:" native"},{en:"natural",cn:"自然的"},{en:"navigate",cn:"导航"},
    {en:"neat",cn:"整洁的"},{en:"necessity",cn:"必要性"},{en:"negative",cn:"消极的"},{en:"neglect",cn:"忽视"},
    {en:"negotiate",cn:"谈判"},{en:"neighbor",cn:"邻居"},{en:"nerve",cn:"神经"},{en:"nervous",cn:"紧张的"},
    {en:"network",cn:"网络"},{en:"neutral",cn:"中性的"},{en:"nevertheless",cn:"然而"},{en:"noble",cn:" noble"},
    {en:"nonsense",cn:"胡说"},{en:"norm",cn:"规范"},{en:"normal",cn:"正常的"},{en:"notable",cn:" notable"},
    {en:"note",cn:"注意"},{en:"notice",cn:" notice"},{en:"notion",cn:"概念"},{en:"notorious",cn:"臭名昭著的"},
    {en:"novel",cn:"小说"},{en:"nowadays",cn:"如今"},{en:"nuclear",cn:"核的"},{en:"numerous",cn:"众多的"},
    {en:"nursery",cn:" nursery"},{en:"nutrition",cn:"营养"},{en:"obey",cn:"服从"},{en:"object",cn:"反对"},
    {en:"objective",cn:"目标"},{en:"obligation",cn:"义务"},{en:"oblige",cn:"迫使"},{en:"observation",cn:"观察"},
    {en:"observe",cn:"观察"},{en:"obstacle",cn:"障碍"},{en:"obtain",cn:"获得"},{en:"obvious",cn:"明显的"},
    {en:"occasion",cn:"场合"},{en:"occupation",cn:"职业"},{en:"occupy",cn:"占领"},{en:"occur",cn:"发生"},
    {en:"offend",cn:"冒犯"},{en:"offense",cn:" offense"},{en:"official",cn:"官方的"},{en:"operate",cn:"操作"},
    {en:"operation",cn:"操作"},{en:"opponent",cn:"对手"},{en:"opportunity",cn:"机会"},{en:"oppose",cn:"反对"},
    {en:"opposite",cn:"相反的"},{en:"optimistic",cn:"乐观的"},{en:"option",cn:"选项"},{en:"ordinary",cn:"普通的"},
    {en:"organ",cn:"器官"},{en:"organic",cn:"有机的"},{en:"organize",cn:"组织"},{en:"origin",cn:" origin"},
    {en:"original",cn:"原始的"},{en:"otherwise",cn:"否则"},{en:"outcome",cn:"结果"},{en:"outer",cn:" outer"},
    {en:"outlet",cn:"出口"},{en:"outline",cn:" outline"},{en:"output",cn:"输出"},{en:"outstanding",cn:" outstanding"},
    {en:"overcome",cn:"克服"},{en:"overlook",cn:"俯瞰"},{en:"overseas",cn:"海外的"},{en:"overtake",cn:"超越"},
    {en:"owe",cn:"欠"},{en:"pace",cn:"步伐"},{en:"pack",cn:"包"},{en:"package",cn:"包裹"},
    {en:"pain",cn:"疼痛"},{en:"panel",cn:"面板"},{en:"panic",cn:"恐慌"},{en:"parade",cn:"游行"},
    {en:"parallel",cn:"平行的"},{en:"parcel",cn:"包裹"},{en:"parliament",cn:"议会"},{en:"partial",cn:"部分的"},
    {en:"participate",cn:"参与"},{en:"particle",cn:"粒子"},{en:"particular",cn:"特定的"},{en:"passage",cn:" passage"},
    {en:"passion",cn:"激情"},{en:"passive",cn:"被动的"},{en:"passport",cn:"护照"},{en:"patent",cn:"专利"},
    {en:"patience",cn:"耐心"},{en:"patient",cn:"病人"},{en:"pattern",cn:"模式"},{en:"pause",cn:"暂停"},
    {en:"peace",cn:"和平"},{en:"peak",cn:"高峰"},{en:"peculiar",cn:" peculiar"},{en:"penalty",cn:"惩罚"},
    {en:"penetrate",cn:"穿透"},{en:"pension",cn:"养老金"},{en:"perceive",cn:"感知"},{en:"percent",cn:"百分之"},
    {en:"percentage",cn:"百分比"},{en:"perception",cn:"感知"},{en:"perfect",cn:"完美的"},{en:"perform",cn:"执行"},
    {en:"performance",cn:" performance"},{en:"period",cn:"时期"},{en:"permanent",cn:" permanent"},{en:"permit",cn:"允许"},
    {en:"persist",cn:"坚持"},{en:"personality",cn:"个性"},{en:"perspective",cn:"视角"},{en:"persuade",cn:"说服"},
    {en:"petition",cn:"请愿"},{en:"phenomenon",cn:"现象"},{en:"philosophy",cn:"哲学"},{en:"physical",cn:"身体的"},
    {en:"pick",cn:"选择"},{en:"pile",cn:"堆"},{en:"pilot",cn:"飞行员"},{en:"pitch",cn:" pitch"},
    {en:"plain",cn:" plain"},{en:"platform",cn:"平台"},{en:"plea",cn:" plea"},{en:"plead",cn:"恳求"},
    {en:"pledge",cn:" pledge"},{en:"plot",cn:"情节"},{en:"plug",cn:"插头"},{en:"plunge",cn:" plunge"},
    {en:"plus",cn:"加"},{en:"poem",cn:"诗"},{en:"poet",cn:"诗人"},{en:"poetry",cn:"诗歌"},
    {en:"poison",cn:"毒药"},{en:"policy",cn:"政策"},{en:"polish",cn:" polish"},{en:"poll",cn:"民意调查"},
    {en:"pollute",cn:"污染"},{en:"pool",cn:"池"},{en:"popular",cn:"流行的"},{en:"populate",cn:"居住于"},
    {en:"population",cn:"人口"},{en:"portable",cn:"便携的"},{en:"portion",cn:"部分"},{en:"portrait",cn:"肖像"},
    {en:"pose",cn:"姿势"},{en:"position",cn:"位置"},{en:"positive",cn:"积极的"},{en:"possess",cn:"拥有"},
    {en:"possession",cn:"财产"},{en:"postpone",cn:"推迟"},{en:"potential",cn:"潜力"},{en:"pour",cn:"倒"},
    {en:"poverty",cn:"贫困"},{en:"power",cn:"力量"},{en:"practical",cn:"实际的"},{en:"practice",cn:"练习"},
    {en:"praise",cn:"赞扬"},{en:"pray",cn:"祈祷"},{en:"preach",cn:"布道"},{en:"precede",cn:"先于"},
    {en:"precious",cn:"珍贵的"},{en:"precise",cn:"精确的"},{en:"predict",cn:"预测"},{en:"dominate",cn:"主导"},
    {en:"preface",cn:"前言"},{en:"prefer",cn:"更喜欢"},{en:"prejudice",cn:"偏见"},{en:"preliminary",cn:"初步的"},
    {en:"premise",cn:"前提"},{en:"premium",cn:"溢价"},{en:"preparation",cn:"准备"},{en:"prepare",cn:"准备"},
    {en:"prescribe",cn:"开处方"},{en:"presence",cn:"存在"},{en:"present",cn:" present"},{en:"preserve",cn:"保存"},
    {en:"pressure",cn:"压力"},{en:"prestige",cn:"声望"},{en:"presume",cn:" presum"},{en:"pretend",cn:"假装"},
    {en:"prevail",cn:"盛行"},{en:"prevent",cn:"防止"},{en:"previous",cn:"以前的"},{en:"primary",cn:"主要的"},
    {en:"prime",cn:" prime"},{en:"primitive",cn:" primitive"},{en:"principal",cn:"校长"},{en:"principle",cn:"原则"},
    {en:"prior",cn:" prior"},{en:"priority",cn:"优先级"},{en:"prison",cn:"监狱"},{en:"privacy",cn:"隐私"},
    {en:"private",cn:"私人的"},{en:"privilege",cn:"特权"},{en:"probe",cn:"探针"},{en:"proceed",cn:"继续"},
    {en:"process",cn:"过程"},{en:"produce",cn:"生产"},{en:"product",cn:"产品"},{en:"production",cn:"生产"},
    {en:"profession",cn:"职业"},{en:"professional",cn:"专业的"},{en:"professor",cn:"教授"},{en:"profile",cn:" profile"},
    {en:"profit",cn:"利润"},{en:"profound",cn:"深刻的"},{en:"program",cn:"程序"},{en:"progress",cn:"进步"},
    {en:"prohibit",cn:"禁止"},{en:"project",cn:"项目"},{en:"prominent",cn:" prominent"},{en:"promise",cn:"承诺"},
    {en:"promote",cn:"促进"},{en:"prompt",cn:"提示"},{en:"proof",cn:" proof"},{en:"proper",cn:" proper"},
    {en:"property",cn:"财产"},{en:"proportion",cn:"比例"},{en:"proposal",cn:"提案"},{en:"propose",cn:"提出"},
    {en:"prospect",cn:"前景"},{en:"prosperity",cn:"繁荣"},{en:"protect",cn:"保护"},{en:"protest",cn:"抗议"},
    {en:"prove",cn:"证明"},{en:"provide",cn:"提供"},{en:"province",cn:"省"},{en:"provoke",cn:"激怒"},
    {en:"publish",cn:"出版"},{en:"punch",cn:" punch"},{en:"punish",cn:"惩罚"},{en:"purchase",cn:"购买"},
    {en:"pure",cn:"纯的"},{en:"pursue",cn:"追求"},{en:"qualify",cn:" qualify"},{en:"quantity",cn:"数量"},
    {en:"quarter",cn:"季度"},{en:"quote",cn:"引用"},{en:"race",cn:" race"},{en:"radical",cn:" radical"},
    {en:"rage",cn:" rage"},{en:"raid",cn:" raid"},{en:"raise",cn:" raise"},{en:"random",cn:"随机的"},
    {en:"range",cn:"范围"},{en:"rank",cn:" rank"},{en:"rapid",cn:" rapid"},{en:"rare",cn:" rare"},
    {en:"rate",cn:" rate"},{en:"ratio",cn:"比率"},{en:"rational",cn:"理性的"},{en:"raw",cn:" raw"},
    {en:"react",cn:"反应"},{en:"reality",cn:"现实"},{en:"realize",cn:"实现"},{en:"realm",cn:" realm"},
    {en:"reasonable",cn:"合理的"},{en:"rebel",cn:" rebel"},{en:"recall",cn:"回忆"},{en:"receipt",cn:"收据"},
    {en:"receive",cn:"接收"},{en:"recent",cn:"最近的"},{en:"recognition",cn:"认可"},{en:"recognize",cn:"识别"},
    {en:"recommend",cn:"推荐"},{en:"recovery",cn:"恢复"},{en:"recruit",cn:"招聘"},{en:"reduce",cn:"减少"},
    {en:"refer",cn:"参考"},{en:"reflect",cn:"反映"},{en:"reform",cn:"改革"},{en:"refugee",cn:"难民"},
    {en:"refuse",cn:"拒绝"},{en:"regard",cn:" regard"},{en:"regime",cn:"政权"},{en:"region",cn:"地区"},
    {en:"register",cn:"注册"},{en:"regulate",cn:" regulate"},{en:"reject",cn:"拒绝"},{en:"relate",cn:" relate"},
    {en:"relation",cn:"关系"},{en:"relative",cn:"相对的"},{en:"release",cn:"发布"},{en:"relevant",cn:"相关的"},
    {en:"relief",cn:"救济"},{en:"relieve",cn:"缓解"},{en:"reluctant",cn:"不情愿的"},{en:"rely",cn:"依赖"},
    {en:"remain",cn:"保持"},{en:"remark",cn:" remark"},{en:"remarkable",cn:" remarkable"},{en:"remedy",cn:" remedy"},
    {en:"remote",cn:" remote"},{en:"remove",cn:"删除"},{en:"render",cn:" render"},{en:"renew",cn:"续订"},
    {en:"rent",cn:"租金"},{en:"repair",cn:"修理"},{en:"repeat",cn:"重复"},{en:"replace",cn:"替换"},
    {en:"report",cn:"报告"},{en:"represent",cn:"代表"},{en:"reproduce",cn:"复制"},{en:"republic",cn:"共和国"},
    {en:"reputation",cn:"声誉"},{en:"request",cn:"请求"},{en:"require",cn:"要求"},{en:"rescue",cn:"营救"},
    {en:"research",cn:"研究"},{en:"resemble",cn:"类似于"},{en:"reserve",cn:"预订"},{en:"reside",cn:"居住"},
    {en:"resign",cn:"辞职"},{en:"resist",cn:"抵抗"},{en:"resolution",cn:"分辨率"},{en:"resolve",cn:"解决"},
    {en:"resort",cn:" resort"},{en:"resource",cn:"资源"},{en:"respond",cn:"响应"},{en:"response",cn:"响应"},
    {en:"responsible",cn:"负责任的"},{en:"restore",cn:"恢复"},{en:"restrain",cn:"抑制"},{en:"restrict",cn:"限制"},
    {en:"retain",cn:"保留"},{en:"retire",cn:"退休"},{en:"reveal",cn:"揭示"},{en:"revenue",cn:"收入"},
    {en:"reverse",cn:"反转"},{en:"review",cn:"审查"},{en:"revolution",cn:"革命"},{en:"reward",cn:"奖励"},
    {en:"rhythm",cn:"节奏"},{en:"rid",cn:"摆脱"},{en:"rigid",cn:" rigid"},{en:"risk",cn:"风险"},
    {en:"rival",cn:" rival"},{en:"role",cn:"角色"},{en:"root",cn:"根"},{en:"rough",cn:" rough"},
    {en:"routine",cn:" routine"},{en:"royal",cn:"皇家的"},{en:"rub",cn:" rub"},{en:"rude",cn:" rude"},
    {en:"ruin",cn:"毁灭"},{en:"rural",cn:"农村的"},{en:"rush",cn:" rush"},{en:"sacrifice",cn:"牺牲"},
    {en:"sample",cn:"样品"},{en:"satellite",cn:"卫星"},{en:"satisfy",cn:"满足"},{en:"scale",cn:"规模"},
    {en:"scan",cn:"扫描"},{en:"scatter",cn:"分散"},{en:"scene",cn:"场景"},{en:"schedule",cn:"日程"},
    {en:"scheme",cn:"方案"},{en:"scholar",cn:"学者"},{en:"science",cn:"科学"},{en:"scope",cn:"范围"},
    {en:"score",cn:"分数"},{en:"scratch",cn:" scratch"},{en:"screen",cn:"屏幕"},{en:"script",cn:"脚本"},
    {en:"search",cn:"搜索"},{en:"season",cn:"季节"},{en:"secure",cn:"安全的"},{en:"seek",cn:"寻找"},
    {en:"segment",cn:" segment"},{en:"select",cn:"选择"},{en:"senior",cn:"高级的"},{en:"sense",cn:"感觉"},
    {en:"sensitive",cn:"敏感的"},{en:"sentence",cn:"句子"},{en:"separate",cn:"分开的"},{en:"sequence",cn:"序列"},
    {en:"series",cn:"系列"},{en:"serious",cn:"严重的"},{en:"serve",cn:"服务"},{en:"session",cn:"会议"},
    {en:"settle",cn:"解决"},{en:"severe",cn:"严重的"},{en:"shadow",cn:"阴影"},{en:"shake",cn:" shake"},
    {en:"shallow",cn:"浅的"},{en:"shame",cn:" shame"},{en:"shape",cn:"形状"},{en:"share",cn:"分享"},
    {en:"sharp",cn:"锋利的"},{en:"shelter",cn:"庇护所"},{en:"shift",cn:" shift"},{en:"shine",cn:" shine"},
    {en:"ship",cn:"船"},{en:"shock",cn:"震惊"},{en:"shoot",cn:" shoot"},{en:"shore",cn:"岸"},
    {en:"shortage",cn:"短缺"},{en:"shrink",cn:"收缩"},{en:"shut",cn:"关闭"},{en:"signal",cn:"信号"},
    {en:"significance",cn:"重要性"},{en:"significant",cn:"重要的"},{en:"silence",cn:"沉默"},{en:"similar",cn:"相似的"},
    {en:"simple",cn:"简单的"},{en:"simulate",cn:"模拟"},{en:"simultaneous",cn:"同时的"},{en:"single",cn:"单个的"},
    {en:"site",cn:"站点"},{en:"situation",cn:"情况"},{en:"skill",cn:"技能"},{en:"skim",cn:" skim"},
    {en:"slap",cn:" slap"},{en:"slave",cn:"奴隶"},{en:"slide",cn:" slide"},{en:"slight",cn:"轻微的"},
    {en:"slip",cn:"滑"},{en:"slope",cn:"斜坡"},{en:"smart",cn:"聪明的"},{en:"smooth",cn:"光滑的"},
    {en:"snap",cn:" snap"},{en:"soak",cn:"浸泡"},{en:"social",cn:"社会的"},{en:"software",cn:"软件"},
    {en:"soil",cn:"土壤"},{en:"solar",cn:"太阳的"},{en:"sole",cn:"唯一的"},{en:"solid",cn:"固体的"},
    {en:"solution",cn:"解决方案"},{en:"solve",cn:"解决"},{en:"somewhat",cn:" somewhat"},{en:"sophisticated",cn:" sophisticated"},
    {en:"sort",cn:"排序"},{en:"soul",cn:"灵魂"},{en:"source",cn:"来源"},{en:"space",cn:"空间"},
    {en:"spare",cn:" spare"},{en:"spark",cn:"火花"},{en:"special",cn:"特殊的"},{en:"species",cn:"物种"},
    {en:"specific",cn:"具体的"},{en:"speculate",cn:"推测"},{en:"speech",cn:"演讲"},{en:"speed",cn:"速度"},
    {en:"spend",cn:"花费"},{en:"sphere",cn:"球体"},{en:"spirit",cn:"精神"},{en:"split",cn:" split"},
    {en:"sponsor",cn:"赞助商"},{en:"spread",cn:"传播"},{en:"spring",cn:"春天"},{en:"spy",cn:"间谍"},
    {en:"squeeze",cn:" squeeze"},{en:"stable",cn:"稳定的"},{en:"staff",cn:" staff"},{en:"stage",cn:"阶段"},
    {en:"stain",cn:" stain"},{en:"stake",cn:" stake"},{en:"stand",cn:" stand"},{en:"standard",cn:"标准"},
    {en:"starve",cn:"饿死"},{en:"state",cn:"状态"},{en:"statistics",cn:"统计"},{en:"status",cn:"状态"},
    {en:"steady",cn:"稳定的"},{en:"steal",cn:"偷"},{en:"steep",cn:"陡峭的"},{en:"stem",cn:" stem"},
    {en:"stick",cn:" stick"},{en:"stimulate",cn:"刺激"},{en:"stock",cn:"股票"},{en:"store",cn:"商店"},
    {en:"storm",cn:"暴风雨"},{en:"straight",cn:" straight"},{en:"strain",cn:" strain"},{en:"strategy",cn:"战略"},
    {en:"strength",cn:"力量"},{en:"stress",cn:"压力"},{en:"stretch",cn:" stretch"},{en:"strict",cn:"严格的"},
    {en:"strike",cn:"罢工"},{en:"string",cn:"字符串"},{en:"strip",cn:" strip"},{en:"stroke",cn:" stroke"},
    {en:"structure",cn:"结构"},{en:"struggle",cn:" struggle"},{en:"stuff",cn:" stuff"},{en:"submit",cn:"提交"},
    {en:"substance",cn:"物质"},{en:"substitute",cn:"替代品"},{en:"subtle",cn:" subtle"},{en:"succeed",cn:"成功"},
    {en:"success",cn:"成功"},{en:"suffer",cn:"遭受"},{en:"sufficient",cn:"足够的"},{en:"suggest",cn:"建议"},
    {en:"suicide",cn:"自杀"},{en:"suit",cn:" suit"},{en:"summarize",cn:"总结"},{en:"summary",cn:"摘要"},
    {en:"supply",cn:"供应"},{en:"support",cn:"支持"},{en:"suppose",cn:"假设"},{en:"suppress",cn:"镇压"},
    {en:"supreme",cn:"最高"},{en:"surface",cn:"表面"},{en:"surgery",cn:"外科手术"},{en:"surplus",cn:" surplus"},
    {en:"surrender",cn:"投降"},{en:"surround",cn:"围绕"},{en:"survey",cn:"调查"},{en:"survive",cn:"幸存"},
    {en:"suspect",cn:"怀疑"},{en:"suspend",cn:"暂停"},{en:"sustain",cn:"维持"},{en:"swallow",cn:" swallow"},
    {en:"swear",cn:"发誓"},{en:"sweep",cn:" sweep"},{en:"swell",cn:" swell"},{en:"swift",cn:" swift"},
    {en:"swing",cn:" swing"},{en:"switch",cn:" switch"},{en:"symbol",cn:"符号"},{en:"sympathy",cn:"同情"},
    {en:"symptom",cn:"症状"},{en:"tackle",cn:" tackle"},{en:"talent",cn:"才能"},{en:"target",cn:"目标"},
    {en:"task",cn:"任务"},{en:"tax",cn:"税"},{en:"team",cn:"团队"},{en:"tear",cn:" tear"},
    {en:"technical",cn:"技术的"},{en:"technique",cn:"技术"},{en:"technology",cn:"技术"},{en:"temperature",cn:"温度"},
    {en:"temporary",cn:"临时的"},{en:"tempt",cn:"诱惑"},{en:"tend",cn:" tend"},{en:"tendency",cn:"趋势"},
    {en:"tender",cn:" tender"},{en:"term",cn:"术语"},{en:"terminal",cn:"终端"},{en:"territory",cn:"领土"},
    {en:"terror",cn:"恐怖"},{en:"testify",cn:"作证"},{en:"text",cn:"文本"},{en:"theme",cn:"主题"},
    {en:"theory",cn:"理论"},{en:"therapy",cn:"治疗"},{en:"therefore",cn:"因此"},{en:"thorough",cn:" thorough"},
    {en:"thought",cn:"思想"},{en:"threat",cn:"威胁"},{en:"threaten",cn:"威胁"},{en:"thrive",cn:"蓬勃发展"},
    {en:"tight",cn:"紧的"},{en:"tip",cn:"提示"},{en:"title",cn:"标题"},{en:"token",cn:"令牌"},
    {en:"tolerate",cn:"容忍"},{en:"tone",cn:" tone"},{en:"topic",cn:"主题"},{en:"tough",cn:" tough"},
    {en:"tour",cn:"旅游"},{en:"trace",cn:" trace"},{en:"track",cn:" track"},{en:"trade",cn:"贸易"},
    {en:"tradition",cn:"传统"},{en:"traffic",cn:"交通"},{en:"transform",cn:"转变"},{en:"translate",cn:"翻译"},
    {en:"transmit",cn:"传输"},{en:"transport",cn:"运输"},{en:"trap",cn:"陷阱"},{en:"treasure",cn:" treasure"},
    {en:"treat",cn:" treat"},{en:"treaty",cn:"条约"},{en:"trend",cn:"趋势"},{en:"trial",cn:" trial"},
    {en:"tribe",cn:"部落"},{en:"trick",cn:" trick"},{en:"trigger",cn:"触发"},{en:"triumph",cn:"胜利"},
    {en:"troop",cn:"部队"},{en:"tropical",cn:"热带的"},{en:"trouble",cn:"麻烦"},{en:"trust",cn:"信任"},
    {en:"tube",cn:"管"},{en:"tune",cn:" tune"},{en:"tunnel",cn:"隧道"},{en:"turbulent",cn:"动荡的"},
    {en:"turn",cn:"转"},{en:"tutor",cn:" tutor"},{en:"twist",cn:" twist"},{en:"typical",cn:"典型的"},
    {en:"ultimate",cn:"最终的"},{en:"undergo",cn:"经历"},{en:"underlie",cn:"构成...的基础"},{en:"undertake",cn:"承担"},
    {en:"uniform",cn:"制服"},{en:"unique",cn:"独特的"},{en:"unite",cn:"联合"},{en:"unity",cn:"统一"},
    {en:"universal",cn:"普遍的"},{en:"urban",cn:"城市的"},{en:"urge",cn:" urge"},{en:"urgent",cn:"紧急的"},
    {en:"usage",cn:"用法"},{en:"utility",cn:"公用事业"},{en:"utilize",cn:"利用"},{en:"utter",cn:" utter"},
    {en:"vacuum",cn:"真空"},{en:"vague",cn:" vague"},{en:"valid",cn:"有效的"},{en:"valley",cn:"山谷"},
    {en:"value",cn:"价值"},{en:"vanish",cn:"消失"},{en:"variable",cn:"变量"},{en:"variety",cn:" variety"},
    {en:"various",cn:"各种的"},{en:"vast",cn:"广阔的"},{en:"vehicle",cn:"车辆"},{en:"venture",cn:" venture"},
    {en:"verify",cn:"验证"},{en:"version",cn:"版本"},{en:"victim",cn:"受害者"},{en:"view",cn:"视图"},
    {en:"violate",cn:"违反"},{en:"violence",cn:"暴力"},{en:"virtual",cn:"虚拟的"},{en:"virtue",cn:"美德"},
    {en:"visible",cn:"可见的"},{en:"vision",cn:"视觉"},{en:"vital",cn:" vital"},{en:"vivid",cn:" vivid"},
    {en:"vocabulary",cn:"词汇"},{en:"volume",cn:"卷"},{en:"voluntary",cn:"自愿的"},{en:"vote",cn:"投票"},
    {en:"vulnerable",cn:"脆弱的"},{en:"wage",cn:"工资"},{en:"wander",cn:" wander"},{en:"warn",cn:"警告"},
    {en:"waste",cn:"浪费"},{en:"wealth",cn:"财富"},{en:"weapon",cn:"武器"},{en:"weigh",cn:"称重"},
    {en:"welfare",cn:"福利"},{en:"wheat",cn:"小麦"},{en:"whereas",cn:" whereas"},{en:"whisper",cn:" whisper"},
    {en:"wicked",cn:"邪恶的"},{en:"widespread",cn:"广泛的"},{en:"wild",cn:"野生的"},{en:"willing",cn:"愿意的"},
    {en:"wind",cn:"风"},{en:"wing",cn:"翅膀"},{en:"wire",cn:"电线"},{en:"wisdom",cn:"智慧"},
    {en:"wise",cn:"明智的"},{en:"wit",cn:"机智"},{en:"withdraw",cn:"撤回"},{en:"withstand",cn:" withstand"},
    {en:"witness",cn:"证人"},{en:"wonder",cn:"奇迹"},{en:"wood",cn:"木头"},{en:"wool",cn:"羊毛"},
    {en:"worth",cn:"价值"},{en:"wound",cn:"伤口"},{en:"wrap",cn:"包裹"},{en:"yield",cn:" yield"},
    {en:"youth",cn:"青年"},{en:"zone",cn:"区域"},{en:"aberration",cn:"偏差"},{en:"abscond",cn:"潜逃"},
    {en:"abstemious",cn:"节制的"},{en:"acerbic",cn:"尖刻的"},{en:"acumen",cn:"敏锐"},{en:"admonish",cn:"告诫"},
    {en:"affable",cn:"和蔼的"},{en:"affluent",cn:"富裕的"},{en:"alacrity",cn:"敏捷"},{en:"altruistic",cn:"利他的"},
    {en:"ambivalent",cn:"矛盾的"},{en:"ameliorate",cn:"改善"},{en:"anachronistic",cn:"时代错误的"},{en:"analogous",cn:"类似的"},
    {en:"anomaly",cn:"异常"},{en:"antipathy",cn:"反感"},{en:"apathy",cn:"冷漠"},{en:"appease",cn:"安抚"},
    {en:"archaic",cn:"过时的"},{en:"arduous",cn:"艰巨的"},{en:"ascetic",cn:"禁欲的"},{en:"assiduous",cn:"勤奋的"},
    {en:"astute",cn:"精明的"},{en:"audacious",cn:"大胆的"},{en:"austere",cn:"朴素的"},{en:"avarice",cn:"贪婪"},
    {en:"aversion",cn:"厌恶"},{en:"banal",cn:"平庸的"},{en:"belligerent",cn:"好战的"},{en:"beneficent",cn:"仁慈的"},
    {en:"benevolent",cn:"善意的"},{en:"berate",cn:"严厉指责"},{en:"bolster",cn:"支持"},{en:"bombastic",cn:"浮夸的"},
    {en:"bourgeois",cn:"资产阶级的"},{en:"brevity",cn:"简洁"},{en:"bucolic",cn:"田园的"},{en:"bumptious",cn:"自大的"},
    {en:"cacophony",cn:"刺耳的声音"},{en:"cajole",cn:"哄骗"},{en:"calumny",cn:"诽谤"},{en:"candid",cn:"坦率的"},
    {en:"capricious",cn:"反复无常的"},{en:"castigate",cn:"惩罚"},{en:"catalyst",cn:"催化剂"},{en:"caustic",cn:"腐蚀性的"},
    {en:"censure",cn:"谴责"},{en:"cerebral",cn:"大脑的"},{en:"charlatan",cn:"江湖骗子"},{en:"chicanery",cn:"诡辩"},
    {en:"circumscribe",cn:"限制"},{en:"circumvent",cn:"规避"},{en:"clandestine",cn:"秘密的"},{en:"clemency",cn:"仁慈"},
    {en:"coerce",cn:"胁迫"},{en:"cogent",cn:"令人信服的"},{en:"collateral",cn:"抵押品"},{en:"commensurate",cn:"相称的"},
    {en:"compelling",cn:"引人注目的"},{en:"complacent",cn:"自满的"},{en:"compliant",cn:"顺从的"},{en:"concomitant",cn:"伴随的"},
    {en:"conducive",cn:"有利于的"},{en:"congenial",cn:"意气相投的"},{en:"conjecture",cn:"推测"},{en:"connive",cn:"共谋"},
    {en:"consecrate",cn:"奉献"},{en:"conspicuous",cn:"显眼的"},{en:"contentious",cn:"有争议的"},{en:"contrite",cn:"悔恨的"},
    {en:"conundrum",cn:"难题"},{en:"copious",cn:"大量的"},{en:"corroborate",cn:"证实"},{en:"cosmopolitan",cn:"世界性的"},
    {en:"credulous",cn:"轻信的"},{en:"cryptic",cn:"神秘的"},{en:"culminate",cn:"达到高潮"},{en:"culpable",cn:"有罪的"},
    {en:"dearth",cn:"缺乏"},{en:"debilitate",cn:"使衰弱"},{en:"decorum",cn:"礼仪"},{en:"deference",cn:"尊重"},
    {en:"deleterious",cn:"有害的"},{en:"delineate",cn:"描绘"},{en:"demagogue",cn:"煽动者"},{en:"denigrate",cn:"诋毁"},
    {en:"deplete",cn:"消耗"},{en:"deprecate",cn:"反对"},{en:"deride",cn:"嘲笑"},{en:"derivative",cn:"衍生的"},
    {en:"desultory",cn:"散漫的"},{en:"detrimental",cn:"有害的"},{en:"diatribe",cn:"抨击"},{en:"didactic",cn:"说教的"},
    {en:"diffident",cn:"缺乏自信的"},{en:"digress",cn:"离题"},{en:"dilatory",cn:"拖延的"},{en:"disaffected",cn:"不满的"},
    {en:"discerning",cn:"有洞察力的"},{en:"disparage",cn:"贬低"},{en:"disparate",cn:"不同的"},{en:"disseminate",cn:"传播"},
    {en:"dissent",cn:"异议"},{en:"dissolution",cn:"溶解"},{en:"dissonance",cn:"不和谐"},{en:"dogmatic",cn:"教条的"},
    {en:"dormant",cn:"休眠的"},{en:"ebullient",cn:"热情洋溢的"},{en:"eclectic",cn:"折衷的"},{en:"effervescent",cn:"热情的"},
    {en:"efficacious",cn:"有效的"},{en:"egregious",cn:"极坏的"},{en:"elicit",cn:"引出"},{en:"embellish",cn:"装饰"},
    {en:"empathy",cn:"同理心"},{en:"emulate",cn:"模仿"},{en:"endemic",cn:"地方性的"},{en:"engender",cn:"引起"},
    {en:"enigma",cn:"谜"},{en:"ennui",cn:"厌倦"},{en:"ephemeral",cn:"短暂的"},{en:"equanimity",cn:"平静"},
    {en:"equivocal",cn:"模棱两可的"},{en:"erudite",cn:"博学的"},{en:"esoteric",cn:"深奥的"},{en:"espouse",cn:"支持"},
    {en:"euphemism",cn:"委婉语"},{en:"exacerbate",cn:"加剧"},{en:"exalt",cn:"赞扬"},{en:"exasperate",cn:"激怒"},
    {en:"exemplary",cn:"模范的"},{en:"exhaustive",cn:"详尽的"},{en:"exonerate",cn:"免除"},{en:"expedient",cn:"权宜的"},
    {en:"expedite",cn:"加速"},{en:"exploitative",cn:"剥削的"},{en:"exponential",cn:"指数的"},{en:"expunge",cn:"删除"},
    {en:"extenuate",cn:"减轻"},{en:"extraneous",cn:"无关的"},{en:"extravagant",cn:"奢侈的"},{en:"facetious",cn:"滑稽的"},
    {en:"fallacious",cn:"谬误的"},{en:"fastidious",cn:"挑剔的"},{en:"fathom",cn:"理解"},{en:"fervent",cn:"热情的"},
    {en:"flagrant",cn:"公然的"},{en:"florid",cn:"华丽的"},{en:"foment",cn:"煽动"},{en:"forestall",cn:"预先阻止"},
    {en:"fortuitous",cn:"偶然的"},{en:"frivolous",cn:"轻浮的"},{en:"frugal",cn:"节俭的"},{en:"furtive",cn:"鬼鬼祟祟的"},
    {en:"futile",cn:"徒劳的"},{en:"garrulous",cn:"话多的"},{en:"gratuitous",cn:"无端的"},{en:"gregarious",cn:"合群的"},
    {en:"hackneyed",cn:"陈腐的"},{en:"hapless",cn:"不幸的"},{en:"harangue",cn:"长篇大论"},{en:"harbinger",cn:"先兆"},
    {en:"hegemony",cn:"霸权"},{en:"heresy",cn:"异端"},{en:"iconoclast",cn:"偶像破坏者"},{en:"idiosyncratic",cn:"特殊的"},
    {en:"ignominious",cn:"耻辱的"},{en:"immutable",cn:"不可变的"},{en:"impede",cn:"阻碍"},{en:"imperious",cn:"专横的"},
    {en:"impervious",cn:"不受影响的"},{en:"impetuous",cn:"冲动的"},{en:"implacable",cn:"不可安抚的"},
    {en:"importune",cn:"纠缠"},{en:"impregnable",cn:"坚不可摧的"},{en:"impromptu",cn:"即兴的"},{en:"impudent",cn:"无礼的"},
    {en:"impugn",cn:"质疑"},{en:"incisive",cn:"深刻的"},{en:"incongruous",cn:"不协调的"},{en:"indifferent",cn:"冷漠的"},
    {en:"indigenous",cn:"本地的"},{en:"indignant",cn:"愤慨的"},{en:"indolent",cn:"懒惰的"},{en:"ineludible",cn:"不可避免的"},
    {en:"inexorable",cn:"不可阻挡的"},{en:"ingenious",cn:"巧妙的"},{en:"ingenuous",cn:"天真的"},
    {en:"innocuous",cn:"无害的"},{en:"inscrutable",cn:"高深莫测的"},{en:"insipid",cn:"乏味的"},{en:"insolent",cn:"傲慢的"},
    {en:"insurgent",cn:"叛乱的"},{en:"intangible",cn:"无形的"},{en:"integral",cn:"完整的"},{en:"intransigent",cn:"不妥协的"},
    {en:"intrepid",cn:"无畏的"},{en:"inundate",cn:"淹没"},{en:"invective",cn:"辱骂"},{en:"inveterate",cn:"根深蒂固的"},
    {en:"irascible",cn:"易怒的"},{en:"irreverent",cn:"不敬的"},{en:"itinerant",cn:"巡回的"},{en:"jubilant",cn:"欢欣鼓舞的"},
    {en:"judicious",cn:"明智的"},{en:"laconic",cn:"简洁的"},{en:"lament",cn:"哀叹"},{en:"languid",cn:"无精打采的"},
    {en:"laudable",cn:"值得赞扬的"},{en:"lethargic",cn:"昏昏欲睡的"},{en:"levity",cn:"轻浮"},{en:"loquacious",cn:"话多的"},
    {en:"lucid",cn:"清晰的"},{en:"magnanimous",cn:"宽宏大量的"},{en:"malevolent",cn:"恶毒的"},{en:"malleable",cn:"可塑的"},
    {en:"mundane",cn:"平凡的"},{en:"munificent",cn:"慷慨的"},{en:"myriad",cn:"无数的"},{en:"nefarious",cn:"邪恶的"},
    {en:"nonchalant",cn:"冷淡的"},{en:"nostalgia",cn:"怀旧"},{en:"novice",cn:"新手"},{en:"nuance",cn:"细微差别"},
    {en:"obdurate",cn:"顽固的"},{en:"obfuscate",cn:"使模糊"},{en:"oblique",cn:"间接的"},{en:"oblivious",cn:"遗忘的"},
    {en:"obscure",cn:"模糊的"},{en:"obsequious",cn:"谄媚的"},{en:"obsolete",cn:"过时的"},{en:"obstinate",cn:"固执的"},
    {en:"obtuse",cn:"迟钝的"},{en:"onerous",cn:"繁重的"},{en:"opaque",cn:"不透明的"},{en:"opportunist",cn:"机会主义者"},
    {en:"opulent",cn:"富裕的"},{en:"ornate",cn:"华丽的"},{en:"orthodox",cn:"正统的"},{en:"ostentatious",cn:"炫耀的"},
    {en:"pacify",cn:"平息"},{en:"paradigm",cn:"范式"},{en:"paradox",cn:"悖论"},{en:"paragon",cn:"典范"},
    {en:"parsimonious",cn:"吝啬的"},{en:"partisan",cn:"党派的"},{en:"patronize",cn:"光顾"},{en:"paucity",cn:"少量"},
    {en:"pedantic",cn:"学究式的"},{en:"penchant",cn:"嗜好"},{en:"penitent",cn:"忏悔的"},{en:"perfunctory",cn:"敷衍的"},
    {en:"pernicious",cn:"有害的"},{en:"perpetuate",cn:"使永久化"},{en:"perspicacious",cn:"敏锐的"},{en:"pertinent",cn:"相关的"},
    {en:"peruse",cn:"细读"},{en:"pervasive",cn:"普遍的"},{en:"petulant",cn:"暴躁的"},{en:"philanthropy",cn:"慈善"},
    {en:"phlegmatic",cn:"冷漠的"},{en:"placate",cn:"安抚"},{en:"platitude",cn:"陈词滥调"},{en:"plausible",cn:"貌似合理的"},
    {en:"plethora",cn:"过多"},{en:"polemical",cn:"好争论的"},{en:"pragmatic",cn:"务实的"},{en:"precarious",cn:"不稳定的"},
    {en:"precedent",cn:"先例"},{en:"precipitate",cn:"促成"},{en:"precocious",cn:"早熟的"},{en:"predilection",cn:"偏爱"},
    {en:"preeminent",cn:"卓越的"},{en:"prescient",cn:"有先见之明的"},{en:"presumptuous",cn:"放肆的"},{en:"prevalent",cn:"流行的"},
    {en:"pristine",cn:"原始的"},{en:"probity",cn:"正直"},{en:"proliferate",cn:"扩散"},{en:"prolific",cn:"多产的"},
    {en:"propensity",cn:"倾向"},{en:"propitious",cn:"吉利的"},{en:"propriety",cn:"得体"},{en:"proscribe",cn:"禁止"},
    {en:"prosaic",cn:"乏味的"},{en:"providence",cn:"天意"},{en:"provocative",cn:"挑衅的"},{en:"prudent",cn:"谨慎的"},
    {en:"pugnacious",cn:"好斗的"},{en:"punctilious",cn:"一丝不苟的"},{en:"punitive",cn:"惩罚性的"},{en:"quandary",cn:"困境"},
    {en:"querulous",cn:"爱抱怨的"},{en:"quiescent",cn:"静止的"},{en:"quintessential",cn:"典型的"},{en:"raconteur",cn:"善于讲故事的人"},
    {en:"rancorous",cn:"怨恨的"},{en:"rationalize",cn:"合理化"},{en:"rebuke",cn:"指责"},{en:"recalcitrant",cn:"顽抗的"},
    {en:"recant",cn:"撤回"},{en:"reciprocate",cn:"回报"},{en:"recluse",cn:"隐士"},{en:"rectify",cn:"纠正"},
    {en:"redolent",cn:"芬芳的"},{en:"redundant",cn:"多余的"},{en:"refute",cn:"反驳"},{en:"relegate",cn:"降级"},
    {en:"remorse",cn:"懊悔"},{en:"renounce",cn:"放弃"},{en:"replete",cn:"充满的"},{en:"reprehensible",cn:"应受谴责的"},
    {en:"repudiate",cn:"拒绝"},{en:"requisite",cn:"必要的"},{en:"rescind",cn:"撤销"},{en:"resilient",cn:"有弹性的"},
    {en:"resolute",cn:"坚决的"},{en:"reticent",cn:"沉默寡言的"},{en:"revere",cn:"尊敬"},{en:"rhetoric",cn:"修辞"},
    {en:"ruminate",cn:"沉思"},{en:"rustic",cn:"乡村的"},{en:"sagacious",cn:"睿智的"},{en:"salient",cn:"突出的"},
    {en:"sanction",cn:"制裁"},{en:"sanguine",cn:"乐观的"},{en:"sardonic",cn:"讽刺的"},{en:"scrupulous",cn:"一丝不苟的"},
    {en:"scrutinize",cn:"仔细审查"},{en:"surreptitious",cn:"秘密的"},{en:"sycophant",cn:"马屁精"},{en:"tacit",cn:"默示的"},
    {en:"taciturn",cn:"沉默寡言的"},{en:"tangential",cn:"离题的"},{en:"temerity",cn:"鲁莽"},{en:"tenacious",cn:"顽强的"},
    {en:"tenuous",cn:"脆弱的"},{en:"transient",cn:"短暂的"},{en:"trepidation",cn:"恐惧"},{en:"truculent",cn:"好斗的"},
    {en:"ubiquitous",cn:"无处不在的"},{en:"unctuous",cn:"油腔滑调的"},{en:"undermine",cn:"破坏"},{en:"unequivocal",cn:"明确的"},
    {en:"unprecedented",cn:"史无前例的"},{en:"untenable",cn:"站不住脚的"},{en:"upbraid",cn:"责骂"},{en:"urbane",cn:"温文尔雅的"},
    {en:"usurp",cn:"篡夺"},{en:"utilitarian",cn:"功利的"},{en:"vacillate",cn:"犹豫"},{en:"venerate",cn:"尊敬"},
    {en:"veracity",cn:"真实性"},{en:"verbose",cn:"冗长的"},{en:"vestige",cn:"遗迹"},{en:"viable",cn:"可行的"},
    {en:"vicarious",cn:"间接的"},{en:"vigilant",cn:"警惕的"},{en:"vilify",cn:"诽谤"},{en:"vindicate",cn:"证明"},
    {en:"vindictive",cn:"怀恨的"},{en:"virulent",cn:"恶毒的"},{en:"visceral",cn:"发自肺腑的"},{en:"vitriolic",cn:"尖刻的"},
    {en:"vociferous",cn:"大声的"},{en:"volatile",cn:"易变的"},{en:"voracious",cn:"贪婪的"},{en:"wanton",cn:"肆意的"},
    {en:"whimsical",cn:"异想天开的"},{en:"zealous",cn:"热心的"},{en:"zenith",cn:"顶点"},
  ],
};
